packages:
  - docs
  - packages/*
  - apps/*
  - tools/*
  - test
  - test/*
  - scripts/*

  - playground/*

onlyBuiltDependencies:
  - '@vvago/vale'
  - core-js
  - esbuild
  - nx
  - sharp
  - unrs-resolver

engineStrict: false
