// Auto-generated by eval-fix-review.mjs — re-run to update
import '@tale-ui/react-styles/index.css';
import * as React from 'react';
import { ChartContainer } from '@tale-ui/charts';
import { AreaChart } from '@tale-ui/charts/area-chart';
import { BarChart } from '@tale-ui/charts/bar-chart';
import { LineChart } from '@tale-ui/charts/line-chart';
import { PieChart } from '@tale-ui/charts/pie-chart';
import { RadarChart } from '@tale-ui/charts/radar-chart';
import { RadialBarChart } from '@tale-ui/charts/radial-bar-chart';
import { AlertDialog } from '@tale-ui/react/alert-dialog';
import { Autocomplete, useFilter } from '@tale-ui/react/autocomplete';
import { Avatar } from '@tale-ui/react/avatar';
import { Badge } from '@tale-ui/react/badge';
import { Banner } from '@tale-ui/react/banner';
import { Breadcrumbs } from '@tale-ui/react/breadcrumbs';
import { Button } from '@tale-ui/react/button';
import { Card } from '@tale-ui/react/card';
import { Checkbox } from '@tale-ui/react/checkbox';
import { CheckboxGroup } from '@tale-ui/react/checkbox-group';
import { ColorArea, parseColor as ColorareaparseColor } from '@tale-ui/react/color-area';
import { ColorField } from '@tale-ui/react/color-field';
import { ColorPicker } from '@tale-ui/react/color-picker';
import { ColorSlider, parseColor } from '@tale-ui/react/color-slider';
import { ColorSwatch } from '@tale-ui/react/color-swatch';
import { ColorSwatchPicker } from '@tale-ui/react/color-swatch-picker';
import { ColorWheel } from '@tale-ui/react/color-wheel';
import { Column } from '@tale-ui/react/column';
import { Combobox } from '@tale-ui/react/combobox';
import { Container } from '@tale-ui/react/container';
import { Dialog } from '@tale-ui/react/dialog';
import { Disclosure } from '@tale-ui/react/disclosure';
import { Drawer } from '@tale-ui/react/drawer';
import { DropZone } from '@tale-ui/react/drop-zone';
import { EmptyState } from '@tale-ui/react/empty-state';
import { FeaturedIcon } from '@tale-ui/react/featured-icon';
import { Field } from '@tale-ui/react/field';
import { FileTrigger } from '@tale-ui/react/file-trigger';
import { FileUpload } from '@tale-ui/react/file-upload';
import { Form } from '@tale-ui/react/form';
import { Icon } from '@tale-ui/react/icon';
import { ImageCropper, centerCrop, cropToFile, makeAspectCrop } from '@tale-ui/react/image-cropper';
import { Input } from '@tale-ui/react/input';
import { Link } from '@tale-ui/react/link';
import { List } from '@tale-ui/react/list';
import { Menu } from '@tale-ui/react/menu';
import { Meter } from '@tale-ui/react/meter';
import { MultiSelect } from '@tale-ui/react/multi-select';
import { NumberField } from '@tale-ui/react/number-field';
import { Pagination } from '@tale-ui/react/pagination';
import { PinInput } from '@tale-ui/react/pin-input';
import { Popover } from '@tale-ui/react/popover';
import { PreviewCard } from '@tale-ui/react/preview-card';
import { ProgressBar } from '@tale-ui/react/progress-bar';
import { ProgressCircle } from '@tale-ui/react/progress-circle';
import { Radio } from '@tale-ui/react/radio';
import { RadioGroup } from '@tale-ui/react/radio-group';
import { Row } from '@tale-ui/react/row';
import { ScrollArea } from '@tale-ui/react/scroll-area';
import { SearchField } from '@tale-ui/react/search-field';
import { Select } from '@tale-ui/react/select';
import { SelectNative } from '@tale-ui/react/select-native';
import { Slider } from '@tale-ui/react/slider';
import { Switch } from '@tale-ui/react/switch';
import { Tabs } from '@tale-ui/react/tabs';
import { TagGroup } from '@tale-ui/react/tag-group';
import { TagSelect } from '@tale-ui/react/tag-select';
import { Text } from '@tale-ui/react/text';
import { TextArea } from '@tale-ui/react/text-area';
import { TextField } from '@tale-ui/react/text-field';
import { ToggleButton } from '@tale-ui/react/toggle-button';
import { ToggleButtonGroup } from '@tale-ui/react/toggle-group';
import { Toolbar } from '@tale-ui/react/toolbar';
import { Tooltip } from '@tale-ui/react/tooltip';
import { Check, Info, SearchX, TriangleAlert, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import type { Crop, PixelCrop } from '@tale-ui/react/image-cropper';

// ── alert-dialog-confirm ──────────────────────────
function EvalAlertDialogConfirm() {
  const [open, setOpen] = useState(false);

  return (
    <AlertDialog.Root isOpen={open} onOpenChange={setOpen}>
      <AlertDialog.Trigger className="tale-button tale-button--danger tale-button--lg">
        Delete Account
      </AlertDialog.Trigger>
      <AlertDialog.Backdrop>
        <AlertDialog.Popup>
          <AlertDialog.Content>
            <AlertDialog.Title>Delete Account?</AlertDialog.Title>
            <AlertDialog.Description>
              This action is permanent and cannot be undone. Your account and all associated data
              will be permanently deleted.
            </AlertDialog.Description>
            <AlertDialog.Actions>
              <Button variant="neutral" size="md" onPress={() => setOpen(false)}>
                Cancel
              </Button>
              <Button variant="danger" size="md" onPress={() => setOpen(false)}>
                Delete
              </Button>
            </AlertDialog.Actions>
          </AlertDialog.Content>
        </AlertDialog.Popup>
      </AlertDialog.Backdrop>
    </AlertDialog.Root>
  );
}

// ── area-chart-revenue ────────────────────────────
const EvalAreaChartRevenuedata = [
  { month: 'Jan', revenue: 42000 },
  { month: 'Feb', revenue: 55800 },
  { month: 'Mar', revenue: 49200 },
  { month: 'Apr', revenue: 63400 },
  { month: 'May', revenue: 71900 },
  { month: 'Jun', revenue: 88500 },
];

function EvalAreaChartRevenue() {
  return (
    <ChartContainer height={300}>
      <AreaChart.Root data={EvalAreaChartRevenuedata}>
        <AreaChart.Grid strokeDasharray="3 3" />
        <AreaChart.XAxis dataKey="month" />
        <AreaChart.YAxis />
        <AreaChart.Tooltip />
        <AreaChart.Area dataKey="revenue" fillOpacity={0.2} />
      </AreaChart.Root>
    </ChartContainer>
  );
}

// ── autocomplete-search ───────────────────────────
const EvalAutocompleteSearchfruits = [
  { id: 'apple', label: 'Apple' },
  { id: 'apricot', label: 'Apricot' },
  { id: 'banana', label: 'Banana' },
  { id: 'blueberry', label: 'Blueberry' },
  { id: 'cherry', label: 'Cherry' },
  { id: 'coconut', label: 'Coconut' },
  { id: 'grape', label: 'Grape' },
  { id: 'kiwi', label: 'Kiwi' },
  { id: 'lemon', label: 'Lemon' },
  { id: 'lime', label: 'Lime' },
  { id: 'mango', label: 'Mango' },
  { id: 'orange', label: 'Orange' },
  { id: 'papaya', label: 'Papaya' },
  { id: 'peach', label: 'Peach' },
  { id: 'pear', label: 'Pear' },
  { id: 'pineapple', label: 'Pineapple' },
  { id: 'plum', label: 'Plum' },
  { id: 'raspberry', label: 'Raspberry' },
  { id: 'strawberry', label: 'Strawberry' },
  { id: 'watermelon', label: 'Watermelon' },
];

function EvalAutocompleteSearch() {
  const { contains } = useFilter({ sensitivity: 'base' });

  return (
    <Autocomplete.Root filter={contains}>
      <Autocomplete.SearchField aria-label="Search EvalAutocompleteSearchfruits">
        <Autocomplete.Input placeholder="Search EvalAutocompleteSearchfruits..." />
      </Autocomplete.SearchField>
      <Autocomplete.ListBox aria-label="Fruits">
        {EvalAutocompleteSearchfruits.map((fruit) => (
          <Autocomplete.Item key={fruit.id} id={fruit.id} textValue={fruit.label}>
            {fruit.label}
          </Autocomplete.Item>
        ))}
        <Autocomplete.Empty>No EvalAutocompleteSearchfruits found.</Autocomplete.Empty>
      </Autocomplete.ListBox>
    </Autocomplete.Root>
  );
}

// ── avatar-group-overflow ─────────────────────────
function EvalAvatarGroupOverflow() {
  return (
    <Avatar.Group size="md">
      <Avatar.Root>
        <Avatar.Fallback>AB</Avatar.Fallback>
      </Avatar.Root>
      <Avatar.Root>
        <Avatar.Fallback>CD</Avatar.Fallback>
      </Avatar.Root>
      <Avatar.Root>
        <Avatar.Fallback>EF</Avatar.Fallback>
      </Avatar.Root>
      <Avatar.Count>+5</Avatar.Count>
    </Avatar.Group>
  );
}

// ── avatar-with-label ─────────────────────────────
function EvalAvatarWithLabel() {
  return (
    <Avatar.LabelGroup size="md">
      <Avatar.Root>
        <Avatar.Image src="/photo.jpg" alt="Jane Doe" />
        <Avatar.Fallback>JD</Avatar.Fallback>
      </Avatar.Root>
      <Avatar.LabelGroupTitle>Jane Doe</Avatar.LabelGroupTitle>
      <Avatar.LabelGroupSubtitle>Product Designer</Avatar.LabelGroupSubtitle>
    </Avatar.LabelGroup>
  );
}

// ── banner-with-actions ───────────────────────────
function EvalBannerWithActions() {
  return (
    <Banner.Root variant="warning">
      <Banner.Icon>
        <Icon icon={TriangleAlert} size="sm" />
      </Banner.Icon>
      <Banner.Title>Update available</Banner.Title>
      <Banner.Description>A new version is ready to install.</Banner.Description>
      <Banner.Actions>
        <Button variant="ghost" size="sm">Later</Button>
        <Button variant="primary" size="sm">Update now</Button>
      </Banner.Actions>
    </Banner.Root>
  );
}

// ── bar-chart-sales ───────────────────────────────
const EvalBarChartSalesdata = [
  { quarter: 'Q1', sales: 42000, profit: 11000 },
  { quarter: 'Q2', sales: 58000, profit: 17500 },
  { quarter: 'Q3', sales: 51000, profit: 14200 },
  { quarter: 'Q4', sales: 73000, profit: 24800 },
];

function EvalBarChartSales() {
  return (
    <Column gap="m">
      <Text variant="heading" as="h2" size="m">Quarterly Sales & Profit</Text>
      <ChartContainer height={320}>
        <BarChart.Root data={EvalBarChartSalesdata}>
          <BarChart.Grid strokeDasharray="3 3" />
          <BarChart.XAxis dataKey="quarter" />
          <BarChart.YAxis />
          <BarChart.Tooltip />
          <BarChart.Legend />
          <BarChart.Bar dataKey="sales" />
          <BarChart.Bar dataKey="profit" />
        </BarChart.Root>
      </ChartContainer>
    </Column>
  );
}

// ── breadcrumbs-nav ───────────────────────────────
function EvalBreadcrumbsNav() {
  return (
    <Breadcrumbs.Root>
      <Breadcrumbs.Item>
        <Breadcrumbs.Link href="/">Home</Breadcrumbs.Link>
      </Breadcrumbs.Item>
      <Breadcrumbs.Item>
        <Breadcrumbs.Link href="/products">Products</Breadcrumbs.Link>
      </Breadcrumbs.Item>
      <Breadcrumbs.Item>
        <Breadcrumbs.Link>Laptops</Breadcrumbs.Link>
      </Breadcrumbs.Item>
    </Breadcrumbs.Root>
  );
}

// ── card-with-content ─────────────────────────────
function EvalCardWithContent() {
  return (
    <Card.Root>
      <Card.Header>
        <Text variant="heading">Welcome to the Platform</Text>
      </Card.Header>
      <Card.Body>
        <Text color="muted">
          Everything you need to build, launch, and scale your product — all in
          one place. Explore our tools and resources to hit the ground running.
        </Text>
      </Card.Body>
      <Card.Footer>
        <Button variant="primary" size="lg">Get Started</Button>
      </Card.Footer>
    </Card.Root>
  );
}

// ── checkbox-group-form ───────────────────────────
function EvalCheckboxGroupForm() {
  return (
    <CheckboxGroup label="Notification Preferences">
      <Checkbox.Root value="email">
        <Checkbox.Indicator><Icon icon={Check} size="sm" /></Checkbox.Indicator>
        Email
      </Checkbox.Root>
      <Checkbox.Root value="sms">
        <Checkbox.Indicator><Icon icon={Check} size="sm" /></Checkbox.Indicator>
        SMS
      </Checkbox.Root>
      <Checkbox.Root value="push">
        <Checkbox.Indicator><Icon icon={Check} size="sm" /></Checkbox.Indicator>
        Push Notifications
      </Checkbox.Root>
    </CheckboxGroup>
  );
}

// ── color-field-hex ───────────────────────────────
function EvalColorFieldHex() {
  return (
    <ColorField.Root>
      <ColorField.Label>Hex color</ColorField.Label>
      <ColorField.Input />
    </ColorField.Root>
  );
}

// ── color-picker-root ─────────────────────────────
function EvalColorPickerRoot() {
  return (
    <ColorPicker.Root defaultValue="hsl(0, 100%, 50%)">
      <ColorArea.Root yChannel="lightness">
        <ColorArea.Thumb />
      </ColorArea.Root>
    </ColorPicker.Root>
  );
}

// ── color-slider-hue ──────────────────────────────
function EvalColorSliderHue() {
  return (
    <ColorSlider.Root channel="hue" defaultValue={parseColor('hsl(0, 100%, 50%)')}>
      <ColorSlider.Label>Hue</ColorSlider.Label>
      <ColorSlider.Output />
      <ColorSlider.Track>
        <ColorSlider.Thumb />
      </ColorSlider.Track>
    </ColorSlider.Root>
  );
}

// ── color-swatch-picker-palette ───────────────────
const EvalColorSwatchPickerPalettePALETTE = [
  '#ef4444', '#f97316', '#eab308', '#22c55e',
  '#06b6d4', '#3b82f6', '#8b5cf6', '#ec4899',
  '#ffffff', '#d1d5db', '#6b7280', '#111827',
];

function EvalColorSwatchPickerPalette() {
  const [color, setColor] = useState(ColorareaparseColor(EvalColorSwatchPickerPalettePALETTE[5]));

  return (
    <Column gap="s">
      <Text>Select a color</Text>
      <ColorSwatchPicker.Root value={color} onChange={setColor}>
        {EvalColorSwatchPickerPalettePALETTE.map((hex) => (
          <ColorSwatchPicker.Item key={hex} color={hex}>
            <ColorSwatch />
          </ColorSwatchPicker.Item>
        ))}
      </ColorSwatchPicker.Root>
      <Text size="s">Selected: {color.toString('css')}</Text>
    </Column>
  );
}

// ── color-wheel-hue ───────────────────────────────
function EvalColorWheelHue() {
  return (
    <ColorWheel.Root defaultValue="hsl(0, 100%, 50%)" outerRadius={100} innerRadius={70}>
      <ColorWheel.Track />
      <ColorWheel.Thumb />
    </ColorWheel.Root>
  );
}

// ── column-form-layout ────────────────────────────
function EvalColumnFormLayout() {
  return (
    <Form onSubmit={(e) => { e.preventDefault(); }}>
      <Column gap="s">
        <TextField.Root name="name">
          <TextField.Label>Name</TextField.Label>
          <TextField.Input placeholder="Enter your name" />
        </TextField.Root>

        <TextField.Root name="email">
          <TextField.Label>Email</TextField.Label>
          <TextField.Input type="email" placeholder="Enter your email" />
        </TextField.Root>

        <Row justify="end">
          <Button type="submit" variant="primary" size="lg">Submit</Button>
        </Row>
      </Column>
    </Form>
  );
}

// ── combobox-search ───────────────────────────────
const EvalComboboxSearchCOUNTRIES = [
  { id: 'af', name: 'Afghanistan' },
  { id: 'al', name: 'Albania' },
  { id: 'dz', name: 'Algeria' },
  { id: 'ar', name: 'Argentina' },
  { id: 'au', name: 'Australia' },
  { id: 'at', name: 'Austria' },
  { id: 'be', name: 'Belgium' },
  { id: 'br', name: 'Brazil' },
  { id: 'ca', name: 'Canada' },
  { id: 'cl', name: 'Chile' },
  { id: 'cn', name: 'China' },
  { id: 'co', name: 'Colombia' },
  { id: 'hr', name: 'Croatia' },
  { id: 'cz', name: 'Czech Republic' },
  { id: 'dk', name: 'Denmark' },
  { id: 'eg', name: 'Egypt' },
  { id: 'fi', name: 'Finland' },
  { id: 'fr', name: 'France' },
  { id: 'de', name: 'Germany' },
  { id: 'gh', name: 'Ghana' },
  { id: 'gr', name: 'Greece' },
  { id: 'hu', name: 'Hungary' },
  { id: 'in', name: 'India' },
  { id: 'id', name: 'Indonesia' },
  { id: 'ie', name: 'Ireland' },
  { id: 'il', name: 'Israel' },
  { id: 'it', name: 'Italy' },
  { id: 'jp', name: 'Japan' },
  { id: 'ke', name: 'Kenya' },
  { id: 'mx', name: 'Mexico' },
  { id: 'nl', name: 'Netherlands' },
  { id: 'nz', name: 'New Zealand' },
  { id: 'ng', name: 'Nigeria' },
  { id: 'no', name: 'Norway' },
  { id: 'pk', name: 'Pakistan' },
  { id: 'pe', name: 'Peru' },
  { id: 'ph', name: 'Philippines' },
  { id: 'pl', name: 'Poland' },
  { id: 'pt', name: 'Portugal' },
  { id: 'ro', name: 'Romania' },
  { id: 'ru', name: 'Russia' },
  { id: 'sa', name: 'Saudi Arabia' },
  { id: 'za', name: 'South Africa' },
  { id: 'kr', name: 'South Korea' },
  { id: 'es', name: 'Spain' },
  { id: 'se', name: 'Sweden' },
  { id: 'ch', name: 'Switzerland' },
  { id: 'th', name: 'Thailand' },
  { id: 'tr', name: 'Turkey' },
  { id: 'ua', name: 'Ukraine' },
  { id: 'ae', name: 'United Arab Emirates' },
  { id: 'gb', name: 'United Kingdom' },
  { id: 'us', name: 'United States' },
  { id: 'vn', name: 'Vietnam' },
];

function EvalComboboxSearch() {
  const [selectedKey, setSelectedKey] = useState<string | null>(null);
  const [inputValue, setInputValue] = useState('');

  const filtered = EvalComboboxSearchCOUNTRIES.filter((c) =>
    c.name.toLowerCase().includes(inputValue.toLowerCase())
  );

  return (
    <Column gap="s" style={{ width: 320 }}>
      <Combobox.Root
        selectedKey={selectedKey}
        onSelectionChange={(key) => setSelectedKey(key as string)}
        inputValue={inputValue}
        onInputChange={setInputValue}
      >
        <Combobox.Label>Country</Combobox.Label>
        <Combobox.InputGroup>
          <Combobox.Input placeholder="Search countries..." />
          <Combobox.Trigger />
        </Combobox.InputGroup>
        <Combobox.Popover>
          <Combobox.ListBox>
            <Combobox.Empty>No countries found.</Combobox.Empty>
            {filtered.map((country) => (
              <Combobox.Item key={country.id} id={country.id} textValue={country.name}>
                {country.name}
              </Combobox.Item>
            ))}
          </Combobox.ListBox>
        </Combobox.Popover>
      </Combobox.Root>
    </Column>
  );
}

// ── container-color-theme ─────────────────────────
function EvalContainerColorTheme() {
  return (
    <Container color="indigo">
      <Card.Root variant="elevated">
        <Card.Header>
          <Text variant="heading" as="h2">Premium Plan</Text>
        </Card.Header>
        <Card.Footer>
          <Button variant="primary" size="lg">Get started</Button>
        </Card.Footer>
      </Card.Root>
    </Container>
  );
}

// ── dialog-destructive ────────────────────────────
function EvalDialogDestructive() {
  const [open, setOpen] = useState(false);

  return (
    <AlertDialog.Root isOpen={open} onOpenChange={setOpen}>
      <AlertDialog.Trigger className="tale-button tale-button--danger tale-button--lg">
        Delete Account
      </AlertDialog.Trigger>
      <AlertDialog.Backdrop>
        <AlertDialog.Popup>
          <AlertDialog.Content>
            <AlertDialog.Title>Delete account</AlertDialog.Title>
            <AlertDialog.Description>
              This action is permanent and cannot be undone. Your account and all associated data will be immediately and irreversibly removed.
            </AlertDialog.Description>
            <AlertDialog.Actions>
              <Button variant="neutral" size="lg" onPress={() => setOpen(false)}>
                Cancel
              </Button>
              <Button variant="danger" size="lg" onPress={() => setOpen(false)}>
                Delete
              </Button>
            </AlertDialog.Actions>
          </AlertDialog.Content>
        </AlertDialog.Popup>
      </AlertDialog.Backdrop>
    </AlertDialog.Root>
  );
}

// ── dialog-dismissable ────────────────────────────
function EvalDialogDismissable() {
  const [open, setOpen] = useState(false);

  return (
    <Dialog.Root isOpen={open} onOpenChange={setOpen}>
      <Dialog.Trigger className="tale-button--primary">Open Dialog</Dialog.Trigger>
      <Dialog.Backdrop isDismissable>
        <Dialog.Popup>
          <Dialog.Close aria-label="Close" />
          <Dialog.Title>Confirm action</Dialog.Title>
          <Dialog.Description>
            Are you sure you want to proceed? This action can be undone later.
          </Dialog.Description>
          <Dialog.Actions>
            <Button variant="neutral" size="md" onPress={() => setOpen(false)}>Cancel</Button>
            <Button variant="primary" size="md" onPress={() => setOpen(false)}>Confirm</Button>
          </Dialog.Actions>
        </Dialog.Popup>
      </Dialog.Backdrop>
    </Dialog.Root>
  );
}

// ── disclosure-panel ──────────────────────────────
const EvalDisclosurePanelfeatures = [
  'Unlimited projects',
  'Priority customer support',
  'Advanced analytics dashboard',
  'Team collaboration tools',
  'Custom integrations via API',
  '99.9% uptime SLA',
];

function EvalDisclosurePanel() {
  return (
    <Disclosure.Root>
      <Disclosure.Trigger>What is included?</Disclosure.Trigger>
      <Disclosure.Panel>
        <List.Root variant="plain">
          {EvalDisclosurePanelfeatures.map((feature) => (
            <List.Item key={feature}>
              <Row align="center" gap="xs">
                <Icon icon={Check} size="sm" />
                <Text variant="text" size="m">{feature}</Text>
              </Row>
            </List.Item>
          ))}
        </List.Root>
      </Disclosure.Panel>
    </Disclosure.Root>
  );
}

// ── divided-list-items ────────────────────────────
function EvalDividedListItems() {
  return (
    <List.Root variant="divided">
      <List.Item>Design Review</List.Item>
      <List.Item>Sprint Planning</List.Item>
      <List.Item>Code Review</List.Item>
      <List.Item>Retrospective</List.Item>
    </List.Root>
  );
}

// ── drawer-with-backdrop ──────────────────────────
function EvalDrawerWithBackdrop() {
  const [open, setOpen] = React.useState(false);

  return (
    <Drawer.Root open={open} onOpenChange={setOpen}>
      <Drawer.Trigger className="tale-button tale-button--primary tale-button--lg">
        Open Settings
      </Drawer.Trigger>
      <Drawer.Backdrop />
      <Drawer.Popup
        style={{
          marginLeft: 'auto',
          width: 360,
          minHeight: '100vh',
          padding: 'var(--space-m)',
        }}
      >
        <Row justify="between" align="center">
          <Drawer.Title>Settings</Drawer.Title>
          <Drawer.Close className="tale-button tale-button--ghost tale-button--md">
            Close
          </Drawer.Close>
        </Row>
      </Drawer.Popup>
    </Drawer.Root>
  );
}

// ── drop-zone-file ────────────────────────────────
function EvalDropZoneFile() {
  return (
    <DropZone onDrop={(e) => console.log('Dropped:', e.items)}>
      <Column gap="s" style={{ alignItems: 'center', padding: '2rem' }}>
        <Text>Drop files here</Text>
        <FileTrigger onSelect={(files) => { if (files) console.log(files); }}>
          <Button size="lg" variant="neutral">Browse files</Button>
        </FileTrigger>
      </Column>
    </DropZone>
  );
}

// ── empty-state-no-results ────────────────────────
function EvalEmptyStateNoResults() {
  return (
    <EmptyState.Root>
      <EmptyState.Icon>
        <FeaturedIcon>
          <Icon icon={SearchX} />
        </FeaturedIcon>
      </EmptyState.Icon>
      <EmptyState.Title>No results</EmptyState.Title>
      <EmptyState.Description>
        Try adjusting your search terms or using different keywords.
      </EmptyState.Description>
    </EmptyState.Root>
  );
}

// ── field-with-validation ─────────────────────────
function EvalFieldWithValidation() {
  return (
    <Input.Root isInvalid>
      <Input.Label>Email address</Input.Label>
      <Input.Input type="email" placeholder="you@example.com" />
      <Input.Description>We'll never share your email with anyone.</Input.Description>
      <Input.ErrorMessage>Please enter a valid email address.</Input.ErrorMessage>
    </Input.Root>
  );
}

// ── file-trigger-upload ───────────────────────────
function EvalFileTriggerUpload() {
  const [fileName, setFileName] = useState<string | null>(null);

  return (
    <Row gap="m" align="center">
      <FileTrigger
        onSelect={(files) => {
          if (files) {
            const file = Array.from(files)[0];
            setFileName(file?.name ?? null);
          }
        }}
      >
        <Button size="lg">Upload file</Button>
      </FileTrigger>
      {fileName && (
        <Text color="muted">
          {fileName}
        </Text>
      )}
    </Row>
  );
}

// ── file-upload-basic ─────────────────────────────
interface UploadEntry {
  id: string;
  name: string;
  size: number;
  progress: number;
  failed: boolean;
}

function EvalFileUploadBasic() {
  const [entries, setEntries] = useState<UploadEntry[]>([]);
  const timers = useRef<Map<string, ReturnType<typeof setInterval>>>(new Map());

  useEffect(() => {
    return () => timers.current.forEach(clearInterval);
  }, []);

  function startSimulatedUpload(id: string) {
    const timer = setInterval(() => {
      setEntries((prev) => {
        const next = prev.map((e) =>
          e.id === id && e.progress < 100
            ? { ...e, progress: Math.min(e.progress + 10, 100) }
            : e,
        );
        if (next.find((e) => e.id === id)?.progress === 100) {
          clearInterval(timer);
          timers.current.delete(id);
        }
        return next;
      });
    }, 200);
    timers.current.set(id, timer);
  }

  function handleDropFiles(fileList: FileList) {
    Array.from(fileList).forEach((file) => {
      const id = `${Date.now()}-${Math.random()}`;
      setEntries((prev) => [
        ...prev,
        { id, name: file.name, size: file.size, progress: 0, failed: false },
      ]);
      startSimulatedUpload(id);
    });
  }

  function handleDelete(id: string) {
    const timer = timers.current.get(id);
    if (timer) {
      clearInterval(timer);
      timers.current.delete(id);
    }
    setEntries((prev) => prev.filter((e) => e.id !== id));
  }

  function handleRetry(id: string) {
    setEntries((prev) =>
      prev.map((e) => (e.id === id ? { ...e, progress: 0, failed: false } : e)),
    );
    startSimulatedUpload(id);
  }

  return (
    <FileUpload.Root>
      <FileUpload.DropZone
        hint="PNG, JPG or PDF (max 5 MB)"
        accept="image/*,application/pdf"
        maxSize={5 * 1024 * 1024}
        allowsMultiple
        onDropFiles={handleDropFiles}
      />
      <FileUpload.List>
        {entries.map((entry) => (
          <FileUpload.ListItemProgressBar
            key={entry.id}
            name={entry.name}
            size={entry.size}
            progress={entry.progress}
            failed={entry.failed}
            onDelete={() => handleDelete(entry.id)}
            onRetry={() => handleRetry(entry.id)}
          />
        ))}
      </FileUpload.List>
    </FileUpload.Root>
  );
}

// ── form-login ────────────────────────────────────
function EvalFormLogin() {
  return (
    <Form validationBehavior="native">
      <Column gap="s">
        <Text variant="heading" as="h1">Sign in</Text>
        <TextField.Root isRequired name="email">
          <TextField.Label>Email</TextField.Label>
          <TextField.Input type="email" placeholder="you@example.com" />
        </TextField.Root>
        <TextField.Root isRequired name="password">
          <TextField.Label>Password</TextField.Label>
          <TextField.Input type="password" placeholder="Enter your password" />
        </TextField.Root>
        <Button type="submit" variant="primary" size="lg">Sign in</Button>
      </Column>
    </Form>
  );
}

// ── image-cropper-basic ───────────────────────────
function EvalImageCropperBasiccenterAspectCrop(mediaWidth: number, mediaHeight: number, aspect: number) {
  return centerCrop(
    makeAspectCrop({ unit: '%', width: 80 }, aspect, mediaWidth, mediaHeight),
    mediaWidth,
    mediaHeight,
  );
}

function EvalImageCropperBasic() {
  const [imageSrc, setImageSrc] = React.useState<string>();
  const [crop, setCrop] = React.useState<Crop>();
  const [completedCrop, setCompletedCrop] = React.useState<PixelCrop>();
  const [previewUrl, setPreviewUrl] = React.useState<string>();

  function handleFileSelect(files: FileList | null) {
    if (!files || files.length === 0) return;
    const reader = new FileReader();
    reader.onload = (e) => {
      setImageSrc(e.target?.result as string);
      setCrop(undefined);
      setCompletedCrop(undefined);
      setPreviewUrl(undefined);
    };
    reader.readAsDataURL(files[0]);
  }

  function handleImageLoad(event: React.SyntheticEvent<HTMLImageElement>) {
    const { naturalWidth: width, naturalHeight: height } = event.currentTarget;
    setCrop(EvalImageCropperBasiccenterAspectCrop(width, height, 1));
  }

  async function handleSave() {
    if (!completedCrop || !imageSrc) return;
    const file = await cropToFile(imageSrc, completedCrop);
    if (file) {
      setPreviewUrl(URL.createObjectURL(file));
    }
  }

  function handleCancel() {
    setImageSrc(undefined);
    setCrop(undefined);
    setCompletedCrop(undefined);
    setPreviewUrl(undefined);
  }

  return (
    <Column gap="l" style={{ maxWidth: 480 }}>
      <Column gap="xs">
        <Text variant="heading" as="h2" size="m">Upload avatar photo</Text>
        <Text color="muted" size="s">
          Select a photo and crop it to a square for your profile.
        </Text>
      </Column>

      {!imageSrc ? (
        <FileTrigger onSelect={handleFileSelect} acceptedFileTypes={['image/*']}>
          <Button variant="neutral" size="lg">Choose photo</Button>
        </FileTrigger>
      ) : (
        <Column gap="m">
          <ImageCropper.Root
            crop={crop}
            onChange={setCrop}
            onComplete={setCompletedCrop}
            aspect={1}
            circularCrop
          >
            <ImageCropper.Img
              src={imageSrc}
              alt="User avatar to crop"
              onLoad={handleImageLoad}
              style={{ maxHeight: 400, width: '100%' }}
            />
          </ImageCropper.Root>

          {previewUrl && (
            <Row gap="s" style={{ alignItems: 'center' }}>
              <Text size="s" color="muted">Preview:</Text>
              <Avatar.Root size="lg">
                <Avatar.Image src={previewUrl} alt="Cropped avatar preview" />
              </Avatar.Root>
            </Row>
          )}

          <Row gap="s" style={{ justifyContent: 'flex-end' }}>
            <Button variant="neutral" size="lg" onPress={handleCancel}>
              Cancel
            </Button>
            <Button variant="primary" size="lg" onPress={handleSave}>
              Save avatar
            </Button>
          </Row>
        </Column>
      )}
    </Column>
  );
}

// ── input-field ───────────────────────────────────
function EvalInputField() {
  return (
    <TextField.Root>
      <TextField.Label>Name</TextField.Label>
      <TextField.Input placeholder="Enter your name" />
    </TextField.Root>
  );
}

// ── line-chart-visitors ───────────────────────────
const EvalLineChartVisitorsdata = [
  { week: 'Week 1', visitors: 3200 },
  { week: 'Week 2', visitors: 4100 },
  { week: 'Week 3', visitors: 3750 },
  { week: 'Week 4', visitors: 5300 },
  { week: 'Week 5', visitors: 4870 },
];

function EvalLineChartVisitors() {
  return (
    <Column gap="s">
      <Text variant="heading" as="h2" size="m">Weekly Website Visitors</Text>
      <Text size="s" color="muted">Visitor counts over the last 5 weeks</Text>
      <ChartContainer height={300}>
        <LineChart.Root data={EvalLineChartVisitorsdata}>
          <LineChart.Grid strokeDasharray="3 3" />
          <LineChart.XAxis dataKey="week" />
          <LineChart.YAxis />
          <LineChart.Tooltip />
          <LineChart.Line dataKey="visitors" dot />
        </LineChart.Root>
      </ChartContainer>
    </Column>
  );
}

// ── list-with-badges ──────────────────────────────
const EvalListWithBadgesmembers = [
  { id: '1', name: 'Alice Johnson', email: 'alice@example.com', active: true },
  { id: '2', name: 'Bob Smith', email: 'bob@example.com', active: false },
  { id: '3', name: 'Carol White', email: 'carol@example.com', active: true },
  { id: '4', name: 'David Lee', email: 'david@example.com', active: true },
  { id: '5', name: 'Eva Martinez', email: 'eva@example.com', active: false },
];

function EvalListWithBadges() {
  return (
    <List.Root variant="divided">
      {EvalListWithBadgesmembers.map((member) => (
        <List.Item key={member.id}>
          <Row justify="between" align="center">
            <Column gap="2xs">
              <Text variant="label" size="m">{member.name}</Text>
              <Text variant="text" size="s" color="muted">{member.email}</Text>
            </Column>
            <Badge variant={member.active ? 'success' : 'neutral'}>
              {member.active ? 'Active' : 'Inactive'}
            </Badge>
          </Row>
        </List.Item>
      ))}
    </List.Root>
  );
}

// ── menu-dropdown ─────────────────────────────────
function EvalMenuDropdown() {
  return (
    <Menu.Root>
      <Menu.Trigger className="tale-button tale-button--neutral tale-button--md">
        File
      </Menu.Trigger>
      <Menu.Popover>
        <Menu.MenuList>
          <Menu.Group>
            <Menu.Header>Create</Menu.Header>
            <Menu.Item id="new">New</Menu.Item>
          </Menu.Group>
          <Menu.Separator />
          <Menu.Group>
            <Menu.Header>Document</Menu.Header>
            <Menu.Item id="open">Open</Menu.Item>
            <Menu.Item id="save">Save</Menu.Item>
          </Menu.Group>
          <Menu.Separator />
          <Menu.Group>
            <Menu.Header>Session</Menu.Header>
            <Menu.Item id="close">Close</Menu.Item>
          </Menu.Group>
        </Menu.MenuList>
      </Menu.Popover>
    </Menu.Root>
  );
}

// ── meter-with-indicator ──────────────────────────
function EvalMeterWithIndicator() {
  return (
    <Meter.Root value={75} minValue={0} maxValue={100}>
      <Meter.Header>
        <Meter.Label>Disk Usage</Meter.Label>
        <Meter.Value>75%</Meter.Value>
      </Meter.Header>
      <Meter.Track>
        <Meter.Indicator value={75} />
      </Meter.Track>
    </Meter.Root>
  );
}

// ── multi-select-frameworks ───────────────────────
type EvalMultiSelectFrameworksSelectionValue = Parameters<
  NonNullable<React.ComponentProps<typeof MultiSelect.Root>['onSelectionChange']>
>[0];

const EvalMultiSelectFrameworksframeworks = [
  { id: 'react', name: 'React' },
  { id: 'vue', name: 'Vue' },
  { id: 'angular', name: 'Angular' },
  { id: 'svelte', name: 'Svelte' },
  { id: 'solid', name: 'SolidJS' },
  { id: 'qwik', name: 'Qwik' },
  { id: 'astro', name: 'Astro' },
  { id: 'remix', name: 'Remix' },
];

function EvalMultiSelectFrameworks() {
  const [selected, setSelected] = React.useState<EvalMultiSelectFrameworksSelectionValue>(new Set());

  const handleReset = () => setSelected(new Set());

  const handleSelectAll = () =>
    setSelected(new Set(EvalMultiSelectFrameworksframeworks.map((f) => f.id)));

  return (
    <MultiSelect.Root
      label="JavaScript Frameworks"
      placeholder="Select EvalMultiSelectFrameworksframeworks"
      description="Choose one or more EvalMultiSelectFrameworksframeworks used in your project."
      items={EvalMultiSelectFrameworksframeworks}
      selectedKeys={selected}
      onSelectionChange={setSelected}
      selectedCountFormatter={(count) =>
        `${count} framework${count === 1 ? '' : 's'} selected`
      }
      onReset={handleReset}
      onSelectAll={handleSelectAll}
    >
      {(item) => (
        <MultiSelect.Item id={item.id} textValue={item.name}>
          {item.name}
        </MultiSelect.Item>
      )}
    </MultiSelect.Root>
  );
}

// ── number-field-quantity ─────────────────────────
function EvalNumberFieldQuantity() {
  return (
    <NumberField.Root defaultValue={1} minValue={1} maxValue={99}>
      <NumberField.Label>Quantity</NumberField.Label>
      <NumberField.Group>
        <NumberField.Decrement />
        <NumberField.Input />
        <NumberField.Increment />
      </NumberField.Group>
    </NumberField.Root>
  );
}

// ── pagination-control ────────────────────────────
function EvalPaginationControl() {
  const [currentPage, setCurrentPage] = useState(3);
  const totalPages = 10;

  return (
    <Pagination.Root aria-label="Results pagination">
      <Pagination.PreviousTrigger
        disabled={currentPage === 1}
        onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
      />

      <Pagination.Item
        page={1}
        current={currentPage === 1}
        onClick={() => setCurrentPage(1)}
      />

      {currentPage > 3 && <Pagination.Ellipsis />}

      {currentPage > 2 && (
        <Pagination.Item
          page={currentPage - 1}
          onClick={() => setCurrentPage(currentPage - 1)}
        />
      )}

      {currentPage !== 1 && currentPage !== totalPages && (
        <Pagination.Item page={currentPage} current />
      )}

      {currentPage < totalPages - 1 && (
        <Pagination.Item
          page={currentPage + 1}
          onClick={() => setCurrentPage(currentPage + 1)}
        />
      )}

      {currentPage < totalPages - 2 && <Pagination.Ellipsis />}

      <Pagination.Item
        page={totalPages}
        current={currentPage === totalPages}
        onClick={() => setCurrentPage(totalPages)}
      />

      <Pagination.NextTrigger
        disabled={currentPage === totalPages}
        onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
      />
    </Pagination.Root>
  );
}

// ── pie-chart-traffic ─────────────────────────────
const EvalPieChartTrafficdata = [
  { name: 'Direct', value: 40 },
  { name: 'Organic', value: 30 },
  { name: 'Referral', value: 20 },
  { name: 'Social', value: 10 },
];

function EvalPieChartTraffic() {
  return (
    <Card.Root>
      <Card.Header>
        <Text variant="heading" as="h2">Website Traffic Sources</Text>
      </Card.Header>
      <Card.Body>
        <ChartContainer height={300}>
          <PieChart.Root>
            <PieChart.Pie data={EvalPieChartTrafficdata} dataKey="value" nameKey="name" outerRadius={110} paddingAngle={3} />
            <PieChart.Tooltip />
            <PieChart.Legend />
          </PieChart.Root>
        </ChartContainer>
      </Card.Body>
    </Card.Root>
  );
}

// ── pin-input-verification ────────────────────────
function EvalPinInputVerification() {
  return (
    <PinInput.Root maxLength={6}>
      <PinInput.Group>
        <PinInput.Slot index={0} />
        <PinInput.Slot index={1} />
        <PinInput.Slot index={2} />
      </PinInput.Group>
      <PinInput.Separator />
      <PinInput.Group>
        <PinInput.Slot index={3} />
        <PinInput.Slot index={4} />
        <PinInput.Slot index={5} />
      </PinInput.Group>
    </PinInput.Root>
  );
}

// ── popover-info ──────────────────────────────────
function EvalPopoverInfo() {
  return (
    <Popover.Root>
      <Popover.Trigger
        aria-label="Feature info"
        className="tale-icon-button tale-icon-button--ghost tale-icon-button--md"
      >
        <Icon icon={Info} />
      </Popover.Trigger>
      <Popover.Popup placement="bottom" offset={8}>
        <Popover.Arrow />
        <Column gap="xs">
          <Popover.Title>Auto-save</Popover.Title>
          <Popover.Description>
            Your changes are saved automatically every 30 seconds. You can also
            press{' '}
            <kbd>⌘ S</kbd>
            {' '}at any time to save manually.
          </Popover.Description>
        </Column>
      </Popover.Popup>
    </Popover.Root>
  );
}

// ── preview-card-hover ────────────────────────────
function EvalPreviewCardHover() {
  return (
    <PreviewCard.Root>
      <PreviewCard.Trigger>
        <Link href="#">Hover over this link</Link>
      </PreviewCard.Trigger>
      <PreviewCard.Popup placement="bottom" offset={8}>
        <PreviewCard.Arrow />
        <PreviewCard.Content aria-label="Link preview">
          <Column gap="s">
            <Text variant="heading">Preview Title</Text>
            <Text color="muted">A short description of the linked content goes here.</Text>
          </Column>
        </PreviewCard.Content>
      </PreviewCard.Popup>
    </PreviewCard.Root>
  );
}

// ── progress-bar-labeled ──────────────────────────
function EvalProgressBarLabeled() {
  return (
    <ProgressBar.Root value={65} minValue={0} maxValue={100}>
      <ProgressBar.Header>
        <ProgressBar.Label>Uploading Files</ProgressBar.Label>
        <ProgressBar.Value>65%</ProgressBar.Value>
      </ProgressBar.Header>
      <ProgressBar.Track>
        <ProgressBar.Indicator value={65} />
      </ProgressBar.Track>
    </ProgressBar.Root>
  );
}

// ── progress-circle-upload ────────────────────────
function EvalProgressCircleUpload() {
  return (
    <Column align="center" gap="s">
      <ProgressCircle.Root value={65} size="lg">
        <ProgressCircle.Track />
        <ProgressCircle.Label>Uploading</ProgressCircle.Label>
        <ProgressCircle.Value />
      </ProgressCircle.Root>
      <Text color="muted">Uploading your file…</Text>
    </Column>
  );
}

// ── radar-chart-skills ────────────────────────────
const EvalRadarChartSkillsdata = [
  { subject: 'Math', score: 80 },
  { subject: 'Science', score: 90 },
  { subject: 'English', score: 70 },
  { subject: 'History', score: 65 },
  { subject: 'Art', score: 85 },
];

function EvalRadarChartSkills() {
  return (
    <Card.Root>
      <Card.Header>
        <Text variant="heading" as="h2">Developer Skills</Text>
      </Card.Header>
      <Card.Body>
        <RadarChart.Root data={EvalRadarChartSkillsdata} width={500} height={400}>
          <RadarChart.PolarGrid />
          <RadarChart.PolarAngleAxis dataKey="subject" />
          <RadarChart.PolarRadiusAxis />
          <RadarChart.Tooltip />
          <RadarChart.Radar dataKey="score" />
        </RadarChart.Root>
      </Card.Body>
    </Card.Root>
  );
}

// ── radial-bar-chart-quarterly ────────────────────
const EvalRadialBarChartQuarterlydata = [
  { name: 'Q1', value: 80, fill: 'var(--color-60)' },
  { name: 'Q2', value: 60, fill: 'var(--color-40)' },
  { name: 'Q3', value: 90, fill: 'var(--color-70)' },
  { name: 'Q4', value: 70, fill: 'var(--color-50)' },
];

function EvalRadialBarChartQuarterly() {
  return (
    <RadialBarChart.Root data={EvalRadialBarChartQuarterlydata} width={400} height={300}>
      <RadialBarChart.RadialBar dataKey="value" />
      <RadialBarChart.Tooltip />
      <RadialBarChart.Legend />
    </RadialBarChart.Root>
  );
}

// ── radio-group-form ──────────────────────────────
function EvalRadioGroupForm() {
  return (
    <RadioGroup label="Plan">
      <Radio.Root value="free">
        <Radio.Indicator />
        Free
      </Radio.Root>
      <Radio.Root value="pro">
        <Radio.Indicator />
        Pro
      </Radio.Root>
      <Radio.Root value="enterprise">
        <Radio.Indicator />
        Enterprise
      </Radio.Root>
    </RadioGroup>
  );
}

// ── scroll-area-list ──────────────────────────────
const EvalScrollAreaListitems = [
  { id: 1, label: 'Dashboard', description: 'Overview of your activity' },
  { id: 2, label: 'Projects', description: 'All active and archived projects' },
  { id: 3, label: 'Team', description: 'Manage members and permissions' },
  { id: 4, label: 'Analytics', description: 'Traffic and engagement metrics' },
  { id: 5, label: 'Billing', description: 'Subscription and invoices' },
  { id: 6, label: 'Integrations', description: 'Third-party app connections' },
  { id: 7, label: 'Settings', description: 'Account and workspace settings' },
  { id: 8, label: 'Help & Support', description: 'Documentation and contact' },
];

function EvalScrollAreaList() {
  return (
    <ScrollArea.Root style={{ height: 280, width: 360 }}>
      <ScrollArea.Viewport>
        <ScrollArea.Content>
          <List.Root variant="divided">
            {EvalScrollAreaListitems.map((item) => (
              <List.Item key={item.id}>
                <Text variant="label">{item.label}</Text>
                <Text size="s" color="muted">{item.description}</Text>
              </List.Item>
            ))}
          </List.Root>
        </ScrollArea.Content>
      </ScrollArea.Viewport>
      <ScrollArea.Scrollbar orientation="vertical">
        <ScrollArea.Thumb />
      </ScrollArea.Scrollbar>
    </ScrollArea.Root>
  );
}

// ── search-field ──────────────────────────────────
function EvalSearchField() {
  return (
    <SearchField.Root defaultValue="Keyboard">
      <SearchField.Label>Search Products</SearchField.Label>
      <SearchField.Input placeholder="Type to search..." />
      <SearchField.ClearButton>
        <Icon icon={X} size="sm" />
      </SearchField.ClearButton>
    </SearchField.Root>
  );
}

// ── select-dropdown ───────────────────────────────
function EvalSelectDropdown() {
  return (
    <Select.Root placeholder="Select a country">
      <Select.Label>Country</Select.Label>
      <Select.Trigger>
        <Select.Value />
        <Select.Icon />
      </Select.Trigger>
      <Select.Popover>
        <Select.ListBox>
          <Select.Item id="us" textValue="United States">United States</Select.Item>
          <Select.Item id="ca" textValue="Canada">Canada</Select.Item>
          <Select.Item id="uk" textValue="United Kingdom">United Kingdom</Select.Item>
          <Select.Item id="au" textValue="Australia">Australia</Select.Item>
        </Select.ListBox>
      </Select.Popover>
    </Select.Root>
  );
}

// ── select-native-country ─────────────────────────
function EvalSelectNativeCountry() {
  return (
    <Field.Root>
      <Field.Label>Country</Field.Label>
      <Field.Control>
        <SelectNative defaultValue="us">
          <option value="us">United States</option>
          <option value="uk">United Kingdom</option>
          <option value="ca">Canada</option>
        </SelectNative>
      </Field.Control>
    </Field.Root>
  );
}

// ── select-with-sections ──────────────────────────
function EvalSelectWithSections() {
  return (
    <Select.Root placeholder="Select a food...">
      <Select.Label>Food</Select.Label>
      <Select.Trigger>
        <Select.Value />
        <Select.Icon />
      </Select.Trigger>
      <Select.Popover>
        <Select.ListBox>
          <Select.Section>
            <Select.Header>Fruits</Select.Header>
            <Select.Item id="apple" textValue="Apple">Apple</Select.Item>
            <Select.Item id="banana" textValue="Banana">Banana</Select.Item>
          </Select.Section>
          <Select.Section>
            <Select.Header>Vegetables</Select.Header>
            <Select.Item id="carrot" textValue="Carrot">Carrot</Select.Item>
            <Select.Item id="broccoli" textValue="Broccoli">Broccoli</Select.Item>
          </Select.Section>
        </Select.ListBox>
      </Select.Popover>
    </Select.Root>
  );
}

// ── slider-volume ─────────────────────────────────
function EvalSliderVolume() {
  return (
    <Slider.Root defaultValue={50} minValue={0} maxValue={100}>
      <Slider.Header>
        <Slider.Label>Volume</Slider.Label>
        <Slider.Output />
      </Slider.Header>
      <Slider.Control>
        <Slider.Track>
          <Slider.Indicator />
          <Slider.Thumb />
        </Slider.Track>
      </Slider.Control>
    </Slider.Root>
  );
}

// ── switch-settings-list ──────────────────────────
function EvalSwitchSettingsList() {
  return (
    <Card.Root>
      <Card.Header>
        <Text variant="title" size="m">Notification Preferences</Text>
      </Card.Header>
      <Card.Body>
        <Column gap="s">
          <Row justify="between" style={{ alignItems: 'center' }}>
            <Text>Email notifications</Text>
            <Switch.Root defaultSelected>
              <Switch.Thumb />
            </Switch.Root>
          </Row>
          <Row justify="between" style={{ alignItems: 'center' }}>
            <Text>Push notifications</Text>
            <Switch.Root>
              <Switch.Thumb />
            </Switch.Root>
          </Row>
          <Row justify="between" style={{ alignItems: 'center' }}>
            <Text>SMS notifications</Text>
            <Switch.Root>
              <Switch.Thumb />
            </Switch.Root>
          </Row>
        </Column>
      </Card.Body>
    </Card.Root>
  );
}

// ── switch-toggle ─────────────────────────────────
function EvalSwitchToggle() {
  return (
    <Switch.Root>
      <Switch.Thumb />
      Enable notifications
    </Switch.Root>
  );
}

// ── tabs-pills-variant ────────────────────────────
function EvalTabsPillsVariant() {
  return (
    <Column gap="xl" style={{ maxWidth: 640, margin: '0 auto', padding: 'var(--space-xl)' }}>
      <Column gap="xs">
        <Text variant="heading" size="l" as="h1">Settings</Text>
        <Text variant="text" color="muted" as="p">
          Manage your account preferences and configurations.
        </Text>
      </Column>

      <Tabs.Root defaultSelectedKey="account">
        <Tabs.List variant="pills">
          <Tabs.Tab id="account">Account</Tabs.Tab>
          <Tabs.Tab id="security">Security</Tabs.Tab>
          <Tabs.Tab id="notifications">Notifications</Tabs.Tab>
          <Tabs.Indicator />
        </Tabs.List>

        <Tabs.Panel id="account">
          <Column gap="s">
            <Text variant="title" size="m" as="h2">Account</Text>
            <Text variant="text" color="muted" as="p">
              Update your personal information, display name, email address, and profile photo.
              Changes made here will be reflected across all services associated with your account.
            </Text>
          </Column>
        </Tabs.Panel>

        <Tabs.Panel id="security">
          <Column gap="s">
            <Text variant="title" size="m" as="h2">Security</Text>
            <Text variant="text" color="muted" as="p">
              Manage your password, two-factor authentication, and active sessions.
              Review recent login activity and revoke access from trusted devices at any time.
            </Text>
          </Column>
        </Tabs.Panel>

        <Tabs.Panel id="notifications">
          <Column gap="s">
            <Text variant="title" size="m" as="h2">Notifications</Text>
            <Text variant="text" color="muted" as="p">
              Choose how and when you receive notifications — via email, push, or in-app alerts.
              Configure digest frequency and opt out of specific notification types.
            </Text>
          </Column>
        </Tabs.Panel>
      </Tabs.Root>
    </Column>
  );
}

// ── tabs-with-panels ──────────────────────────────
function EvalTabsWithPanels() {
  return (
    <Tabs.Root defaultSelectedKey="overview">
      <Tabs.List>
        <Tabs.Tab id="overview">Overview</Tabs.Tab>
        <Tabs.Tab id="features">Features</Tabs.Tab>
        <Tabs.Tab id="pricing">Pricing</Tabs.Tab>
        <Tabs.Indicator />
      </Tabs.List>
      <Tabs.Panel id="overview">
        <Text>
          Get a high-level look at what we offer. Our platform is designed to
          help teams collaborate efficiently, ship faster, and build products
          that customers love — all from a single, unified workspace.
        </Text>
      </Tabs.Panel>
      <Tabs.Panel id="features">
        <Text>
          From real-time collaboration and version control to advanced analytics
          and integrations with your favourite tools, our feature set is built
          to grow with your team. Everything you need is available out of the
          box with no complex setup required.
        </Text>
      </Tabs.Panel>
      <Tabs.Panel id="pricing">
        <Text>
          We offer flexible plans for individuals, growing teams, and
          enterprises. Start free with our generous free tier, upgrade when you
          need more power, and only pay for what you use — no hidden fees or
          long-term contracts.
        </Text>
      </Tabs.Panel>
    </Tabs.Root>
  );
}

// ── tag-group-skills ──────────────────────────────
function EvalTagGroupSkills() {
  return (
    <TagGroup.Root>
      <TagGroup.Label>Skills</TagGroup.Label>
      <TagGroup.List>
        <TagGroup.Tag id="react">React</TagGroup.Tag>
        <TagGroup.Tag id="typescript">TypeScript</TagGroup.Tag>
        <TagGroup.Tag id="css">CSS</TagGroup.Tag>
      </TagGroup.List>
    </TagGroup.Root>
  );
}

// ── tag-select-team-members ───────────────────────
type EvalTagSelectTeamMembersSelectionValue = Parameters<NonNullable<React.ComponentProps<typeof TagSelect.Root>['onSelectionChange']>>[0];

const EvalTagSelectTeamMembersmembers = [
  { id: 'alice', name: 'Alice Johnson' },
  { id: 'bob', name: 'Bob Smith' },
  { id: 'carol', name: 'Carol White' },
  { id: 'dan', name: 'Dan Brown' },
  { id: 'eva', name: 'Eva Martinez' },
];

function EvalTagSelectTeamMembers() {
  const [selected, setSelected] = React.useState<EvalTagSelectTeamMembersSelectionValue>(
    new Set(['alice', 'bob']),
  );

  return (
    <TagSelect.Root
      label="Team EvalTagSelectTeamMembersmembers"
      placeholder="Search EvalTagSelectTeamMembersmembers…"
      description="Select all EvalTagSelectTeamMembersmembers who should have access to this project."
      items={EvalTagSelectTeamMembersmembers}
      selectedKeys={selected}
      onSelectionChange={setSelected}
    >
      {(item) => (
        <TagSelect.Item id={item.id} textValue={item.name}>
          {item.name}
        </TagSelect.Item>
      )}
    </TagSelect.Root>
  );
}

// ── text-area-input ───────────────────────────────
function EvalTextAreaInput() {
  return (
    <TextArea.Root>
      <TextArea.Label>Bio</TextArea.Label>
      <TextArea.TextArea placeholder="Tell us about yourself" />
    </TextArea.Root>
  );
}

// ── text-input-field ──────────────────────────────
function EvalTextInputField() {
  return (
    <TextField.Root>
      <TextField.Label>Full Name</TextField.Label>
      <TextField.Input />
      <TextField.Description>Enter your first and last name as they appear on your ID.</TextField.Description>
    </TextField.Root>
  );
}

// ── toggle-button-group-alignment ─────────────────
function EvalToggleButtonGroupAlignment() {
  return (
    <ToggleButtonGroup aria-label="Text alignment" selectionMode="single">
      <ToggleButton>Left</ToggleButton>
      <ToggleButton>Center</ToggleButton>
      <ToggleButton>Right</ToggleButton>
    </ToggleButtonGroup>
  );
}

// ── toolbar-actions ───────────────────────────────
function EvalToolbarActions() {
  const [bold, setBold] = useState(false);
  const [italic, setItalic] = useState(false);
  const [underline, setUnderline] = useState(false);

  return (
    <Toolbar.Root aria-label="Formatting">
      <Toolbar.Group>
        <ToggleButton isSelected={bold} onChange={setBold}>Bold</ToggleButton>
        <ToggleButton isSelected={italic} onChange={setItalic}>Italic</ToggleButton>
        <ToggleButton isSelected={underline} onChange={setUnderline}>Underline</ToggleButton>
      </Toolbar.Group>
    </Toolbar.Root>
  );
}

// ── tooltip-button ────────────────────────────────
function EvalTooltipButton() {
  return (
    <Tooltip.Root>
      <Tooltip.Trigger className="tale-button tale-button--primary tale-button--lg">
        Save
      </Tooltip.Trigger>
      <Tooltip.Popup placement="top" offset={8}>
        <Tooltip.Arrow />
        Save changes
      </Tooltip.Popup>
    </Tooltip.Root>
  );
}

export default function EvalReview() {
  return (
    <div className="eval-review">
      <div className="eval-review__header">
        <h1>Eval Review</h1>
        <p>Generated code for 64 golden prompts. Visual L4 inspection.</p>
      </div>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">alert-dialog-confirm</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Create a confirmation dialog triggered by a 'Delete Account' button. The dialog should have a title 'Delete Account?', a description warning that this action is permanent, and two action buttons: 'Cancel' (neutral) and 'Delete' (danger).</p>
        <div className="eval-review__preview">
          <EvalAlertDialogConfirm />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">area-chart-revenue</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show an area chart displaying monthly revenue data for 6 months (Jan through Jun) with a grid, axes, and tooltip.</p>
        <div className="eval-review__preview">
          <EvalAreaChartRevenue />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">autocomplete-search</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show an autocomplete component for searching and filtering a list of fruits.</p>
        <div className="eval-review__preview">
          <EvalAutocompleteSearch />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">avatar-group-overflow</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a group of 3 stacked overlapping avatars with a '+5' overflow count indicator.</p>
        <div className="eval-review__preview">
          <EvalAvatarGroupOverflow />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">avatar-with-label</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a user avatar with their name and role displayed beside it using a label group.</p>
        <div className="eval-review__preview">
          <EvalAvatarWithLabel />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">banner-with-actions</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a warning banner with title 'Update available', description 'A new version is ready to install.', and two action buttons: 'Later' (ghost) and 'Update now' (primary).</p>
        <div className="eval-review__preview">
          <EvalBannerWithActions />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">bar-chart-sales</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a bar chart comparing sales and profit for Q1 through Q4 with a legend and tooltip.</p>
        <div className="eval-review__preview">
          <EvalBarChartSales />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">breadcrumbs-nav</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a breadcrumb navigation trail: Home &gt; Products &gt; Laptops.</p>
        <div className="eval-review__preview">
          <EvalBreadcrumbsNav />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">card-with-content</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Create a card with a header displaying a title, a body with descriptive text, and a footer containing a primary action button labeled 'Get Started'.</p>
        <div className="eval-review__preview">
          <EvalCardWithContent />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">checkbox-group-form</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Create a checkbox group labeled 'Notification Preferences' with three checkboxes: 'Email', 'SMS', and 'Push Notifications'. Each checkbox should have a check icon indicator.</p>
        <div className="eval-review__preview">
          <EvalCheckboxGroupForm />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">color-field-hex</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a hex color input field with a label.</p>
        <div className="eval-review__preview">
          <EvalColorFieldHex />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">color-picker-root</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a color picker using ColorPicker.Root with a ColorArea.Root child — import both ColorPicker from '@tale-ui/react/color-picker' and ColorArea from '@tale-ui/react/color-area'. Use &lt;ColorArea.Root&gt; (NOT &lt;ColorArea&gt;) inside ColorPicker.Root. Do NOT use useState or import from @internationalized/color. Use defaultValue with a plain CSS string on ColorPicker.Root.</p>
        <div className="eval-review__preview">
          <EvalColorPickerRoot />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">color-slider-hue</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a hue color slider with a label and a live value output.</p>
        <div className="eval-review__preview">
          <EvalColorSliderHue />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">color-swatch-picker-palette</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a palette of selectable color swatches using ColorSwatchPicker.</p>
        <div className="eval-review__preview">
          <EvalColorSwatchPickerPalette />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">color-wheel-hue</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a circular color wheel for selecting a hue — do NOT use useState or import from @internationalized/color. Use defaultValue with a plain CSS string.</p>
        <div className="eval-review__preview">
          <EvalColorWheelHue />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">column-form-layout</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a vertical form layout using Column with a Name field, an Email field, and a submit button row right-aligned.</p>
        <div className="eval-review__preview">
          <EvalColumnFormLayout />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">combobox-search</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a combobox for searching and selecting a country from a dropdown list.</p>
        <div className="eval-review__preview">
          <EvalComboboxSearch />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">container-color-theme</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a card section with an indigo color theme applied using Container, containing a heading 'Premium Plan' and a primary button 'Get started'.</p>
        <div className="eval-review__preview">
          <EvalContainerColorTheme />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">dialog-destructive</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a destructive dialog triggered by a 'Delete Account' button. The dialog should have a title 'Delete account', a warning description that this action is permanent, and Cancel + Delete action buttons.</p>
        <div className="eval-review__preview">
          <EvalDialogDestructive />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">dialog-dismissable</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Create a dismissable dialog with a title, description, and a cancel/confirm button pair.</p>
        <div className="eval-review__preview">
          <EvalDialogDismissable />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">disclosure-panel</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a 'What is included?' disclosure panel that reveals a list of included features when expanded.</p>
        <div className="eval-review__preview">
          <EvalDisclosurePanel />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">divided-list-items</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Create a divided list displaying four items: 'Design Review', 'Sprint Planning', 'Code Review', and 'Retrospective'.</p>
        <div className="eval-review__preview">
          <EvalDividedListItems />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">drawer-with-backdrop</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Create a side drawer that opens from the right with a backdrop, title &quot;Settings&quot;, and a close button.</p>
        <div className="eval-review__preview eval-review__preview--drawer">
          <EvalDrawerWithBackdrop />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">drop-zone-file</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a file drop zone with 'Drop files here' text.</p>
        <div className="eval-review__preview">
          <EvalDropZoneFile />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">empty-state-no-results</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show an empty state with heading 'No results' and a description suggesting the user try different search terms.</p>
        <div className="eval-review__preview">
          <EvalEmptyStateNoResults />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">field-with-validation</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a Field wrapper with a label, description helper text, and an error message.</p>
        <div className="eval-review__preview">
          <EvalFieldWithValidation />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">file-trigger-upload</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a file upload button using FileTrigger that displays the selected filename.</p>
        <div className="eval-review__preview">
          <EvalFileTriggerUpload />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">file-upload-basic</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a file upload area that accepts images and PDFs up to 5 MB, and displays uploaded files with a progress bar.</p>
        <div className="eval-review__preview">
          <EvalFileUploadBasic />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">form-login</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a login form with email and password fields and a submit button, using native validation.</p>
        <div className="eval-review__preview">
          <EvalFormLogin />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">image-cropper-basic</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show an image cropper for a user avatar photo with a 1:1 aspect ratio.</p>
        <div className="eval-review__preview">
          <EvalImageCropperBasic />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">input-field</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a text input field with a label and placeholder 'Enter your name'.</p>
        <div className="eval-review__preview">
          <EvalInputField />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">line-chart-visitors</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a line chart displaying weekly website visitor counts over 5 weeks with a grid, axes, and tooltip.</p>
        <div className="eval-review__preview">
          <EvalLineChartVisitors />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">list-with-badges</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a divided list of team members where each item displays a name and email on the left, and a status badge (Active or Inactive) on the right.</p>
        <div className="eval-review__preview">
          <EvalListWithBadges />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">menu-dropdown</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a dropdown menu triggered by a button with file actions: New, Open, Save, and Close, separated into groups.</p>
        <div className="eval-review__preview">
          <EvalMenuDropdown />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">meter-with-indicator</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Create a meter showing 75% disk usage with a label and track.</p>
        <div className="eval-review__preview">
          <EvalMeterWithIndicator />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">multi-select-frameworks</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a MultiSelect for choosing JavaScript frameworks. Include a label, placeholder, description, and show the selected count in the trigger. Include Reset and Select All footer buttons.</p>
        <div className="eval-review__preview">
          <EvalMultiSelectFrameworks />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">number-field-quantity</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a quantity number field with a label, minimum value of 1, and maximum value of 99.</p>
        <div className="eval-review__preview">
          <EvalNumberFieldQuantity />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">pagination-control</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a pagination control displaying page 3 of 10 with previous/next buttons.</p>
        <div className="eval-review__preview">
          <EvalPaginationControl />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">pie-chart-traffic</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a pie chart breaking down website traffic sources: Direct (40%), Organic (30%), Referral (20%), and Social (10%), with a legend and tooltip.</p>
        <div className="eval-review__preview">
          <EvalPieChartTraffic />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">pin-input-verification</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a 6-digit PIN input for verification codes, split into two groups of 3 with a separator.</p>
        <div className="eval-review__preview">
          <EvalPinInputVerification />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">popover-info</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show an info button that opens a popover with help text explaining a feature.</p>
        <div className="eval-review__preview">
          <EvalPopoverInfo />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">preview-card-hover</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a link that displays a preview card popup with a title and description on hover.</p>
        <div className="eval-review__preview">
          <EvalPreviewCardHover />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">progress-bar-labeled</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Create a progress bar at 65% completion with a label that says 'Uploading Files' and a value display showing '65%'.</p>
        <div className="eval-review__preview">
          <EvalProgressBarLabeled />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">progress-circle-upload</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show an upload progress circle at 65% completion.</p>
        <div className="eval-review__preview">
          <EvalProgressCircleUpload />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">radar-chart-skills</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a radar chart displaying a developer's skill scores across 5 subjects: Math (80), Science (90), English (70), History (65), and Art (85), with a polar grid and tooltip.</p>
        <div className="eval-review__preview">
          <EvalRadarChartSkills />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">radial-bar-chart-quarterly</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a radial bar chart displaying quarterly performance values (Q1: 80, Q2: 60, Q3: 90, Q4: 70) with a legend and tooltip.</p>
        <div className="eval-review__preview">
          <EvalRadialBarChartQuarterly />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">radio-group-form</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a radio group for plan selection with Free, Pro, and Enterprise options.</p>
        <div className="eval-review__preview">
          <EvalRadioGroupForm />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">scroll-area-list</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a scroll area containing a list of 8 items inside a fixed-height container.</p>
        <div className="eval-review__preview">
          <EvalScrollAreaList />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">search-field</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Create a search field with a visible label that says 'Search Products', a placeholder 'Type to search...', a default value of 'Keyboard', and a clear button with an X icon.</p>
        <div className="eval-review__preview">
          <EvalSearchField />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">select-dropdown</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a country selector dropdown with a label 'Country', a placeholder 'Select a country', and four options: United States, Canada, United Kingdom, and Australia.</p>
        <div className="eval-review__preview">
          <EvalSelectDropdown />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">select-native-country</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a native select dropdown for country selection with options for US, UK, and Canada.</p>
        <div className="eval-review__preview">
          <EvalSelectNativeCountry />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">select-with-sections</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a food category selector with sections: a 'Fruits' section with Apple and Banana, and a 'Vegetables' section with Carrot and Broccoli.</p>
        <div className="eval-review__preview">
          <EvalSelectWithSections />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">slider-volume</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a volume slider ranging from 0 to 100 with a default value of 50.</p>
        <div className="eval-review__preview">
          <EvalSliderVolume />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">switch-settings-list</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a settings card with three notification preference switches: 'Email notifications' (on by default), 'Push notifications', and 'SMS notifications'.</p>
        <div className="eval-review__preview">
          <EvalSwitchSettingsList />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">switch-toggle</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a switch labeled 'Enable notifications'.</p>
        <div className="eval-review__preview">
          <EvalSwitchToggle />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">tabs-pills-variant</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a settings page with pill-style tabs: Account, Security, and Notifications, each with a content panel describing that section.</p>
        <div className="eval-review__preview">
          <EvalTabsPillsVariant />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">tabs-with-panels</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Create a tabbed interface with three tabs: 'Overview', 'Features', and 'Pricing'. Each tab should have a corresponding content panel with a short paragraph describing that section. The first tab should be selected by default.</p>
        <div className="eval-review__preview">
          <EvalTabsWithPanels />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">tag-group-skills</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a tag group with React, TypeScript, and CSS skill tags.</p>
        <div className="eval-review__preview">
          <EvalTagGroupSkills />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">tag-select-team-members</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a TagSelect for picking team members. Include a label, placeholder, and description. Pre-select two members.</p>
        <div className="eval-review__preview">
          <EvalTagSelectTeamMembers />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">text-area-input</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a bio textarea with a label and a placeholder saying 'Tell us about yourself'.</p>
        <div className="eval-review__preview">
          <EvalTextAreaInput />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">text-input-field</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Create a text input field with a label that says 'Full Name' and a description below it that says 'Enter your first and last name as they appear on your ID.'</p>
        <div className="eval-review__preview">
          <EvalTextInputField />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">toggle-button-group-alignment</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a toggle button group for text alignment with Left, Center, and Right options.</p>
        <div className="eval-review__preview">
          <EvalToggleButtonGroupAlignment />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">toolbar-actions</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a toolbar with Bold, Italic, and Underline action buttons.</p>
        <div className="eval-review__preview">
          <EvalToolbarActions />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">tooltip-button</code>
          <span className="eval-review__difficulty">[medium]</span>
        </div>
        <p className="eval-review__prompt">Show a save button with a tooltip that says 'Save changes'.</p>
        <div className="eval-review__preview">
          <EvalTooltipButton />
        </div>
      </section>
    </div>
  );
}
