// Auto-generated by eval-fix-review.mjs — re-run to update
import '@tale-ui/react-styles/index.css';
import { Badge } from '@tale-ui/react/badge';
import { Button } from '@tale-ui/react/button';
import { Icon } from '@tale-ui/react/icon';
import { IconButton } from '@tale-ui/react/icon-button';
import { Image } from '@tale-ui/react/image';
import { Link } from '@tale-ui/react/link';
import { Separator } from '@tale-ui/react/separator';
import { Spinner } from '@tale-ui/react/spinner';
import { Text } from '@tale-ui/react/text';
import { Trash2 } from 'lucide-react';

// ── avatar-image ──────────────────────────────────
function EvalAvatarImage() {
  return (
    <Image
      src="/photo.jpg"
      alt="A mountain landscape"
      radius="md"
      width={200}
      height={150}
    />
  );
}

// ── horizontal-separator ──────────────────────────
function EvalHorizontalSeparator() {
  return <Separator />;
}

// ── icon-button-delete ────────────────────────────
function EvalIconButtonDelete() {
  return (
    <IconButton aria-label="Delete item" variant="danger">
      <Icon icon={Trash2} />
    </IconButton>
  );
}

// ── loading-spinner ───────────────────────────────
function EvalLoadingSpinner() {
  return (
    <div className="flex--col center--hv gap--s">
      <Spinner />
      <Text color="muted">Loading data...</Text>
    </div>
  );
}

// ── muted-text ────────────────────────────────────
function EvalMutedText() {
  return (
    <Text color="muted">This action cannot be undone.</Text>
  );
}

// ── primary-button ────────────────────────────────
function EvalPrimaryButton() {
  return <Button variant="primary">Save</Button>;
}

// ── status-badge ──────────────────────────────────
function EvalStatusBadge() {
  return (
    <Badge variant="success">Active</Badge>
  );
}

// ── styled-link ───────────────────────────────────
function EvalStyledLink() {
  return (
    <Link href="https://example.com" target="_blank">
      Visit Example
    </Link>
  );
}

export default function EvalReview() {
  return (
    <div className="eval-review">
      <div className="eval-review__header">
        <h1>Eval Review</h1>
        <p>Generated code for 8 golden prompts. Visual L4 inspection.</p>
      </div>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">avatar-image</code>
          <span className="eval-review__difficulty">[simple]</span>
        </div>
        <p className="eval-review__prompt">Create a 200x150 image with rounded corners showing a photo at &quot;/photo.jpg&quot; with alt text &quot;A mountain landscape&quot;.</p>
        <div className="eval-review__preview">
          <EvalAvatarImage />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">horizontal-separator</code>
          <span className="eval-review__difficulty">[simple]</span>
        </div>
        <p className="eval-review__prompt">Create a horizontal separator line.</p>
        <div className="eval-review__preview">
          <EvalHorizontalSeparator />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">icon-button-delete</code>
          <span className="eval-review__difficulty">[simple]</span>
        </div>
        <p className="eval-review__prompt">Create a danger-styled icon button with a trash icon and an aria-label of &quot;Delete item&quot;.</p>
        <div className="eval-review__preview">
          <EvalIconButtonDelete />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">loading-spinner</code>
          <span className="eval-review__difficulty">[simple]</span>
        </div>
        <p className="eval-review__prompt">Create a loading spinner with the label &quot;Loading data...&quot;.</p>
        <div className="eval-review__preview">
          <EvalLoadingSpinner />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">muted-text</code>
          <span className="eval-review__difficulty">[simple]</span>
        </div>
        <p className="eval-review__prompt">Create a muted secondary text paragraph that says &quot;This action cannot be undone.&quot;</p>
        <div className="eval-review__preview">
          <EvalMutedText />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">primary-button</code>
          <span className="eval-review__difficulty">[simple]</span>
        </div>
        <p className="eval-review__prompt">Create a primary button that says &quot;Save&quot;.</p>
        <div className="eval-review__preview">
          <EvalPrimaryButton />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">status-badge</code>
          <span className="eval-review__difficulty">[simple]</span>
        </div>
        <p className="eval-review__prompt">Create a success badge that displays the text &quot;Active&quot;.</p>
        <div className="eval-review__preview">
          <EvalStatusBadge />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">styled-link</code>
          <span className="eval-review__difficulty">[simple]</span>
        </div>
        <p className="eval-review__prompt">Create a link to &quot;https://example.com&quot; that opens in a new tab with the text &quot;Visit Example&quot;.</p>
        <div className="eval-review__preview">
          <EvalStyledLink />
        </div>
      </section>
    </div>
  );
}
