// Auto-generated by eval-fix-review.mjs — re-run to update
import '@tale-ui/react-styles/index.css';
import * as React from 'react';
import { Accordion } from '@tale-ui/react/accordion';
import { Badge } from '@tale-ui/react/badge';
import { Banner } from '@tale-ui/react/banner';
import { Button } from '@tale-ui/react/button';
import { Calendar } from '@tale-ui/react/calendar';
import { Card } from '@tale-ui/react/card';
import { Carousel } from '@tale-ui/react/carousel';
import { ColorArea } from '@tale-ui/react/color-area';
import { ColorSlider } from '@tale-ui/react/color-slider';
import { Column } from '@tale-ui/react/column';
import { ContextMenu } from '@tale-ui/react/context-menu';
import { DateField } from '@tale-ui/react/date-field';
import { DatePicker } from '@tale-ui/react/date-picker';
import { DateRangePicker } from '@tale-ui/react/date-range-picker';
import { Fieldset } from '@tale-ui/react/fieldset';
import { GridList } from '@tale-ui/react/grid-list';
import { Icon } from '@tale-ui/react/icon';
import { IconButton } from '@tale-ui/react/icon-button';
import { Image } from '@tale-ui/react/image';
import { Link } from '@tale-ui/react/link';
import { Menu } from '@tale-ui/react/menu';
import { Menubar } from '@tale-ui/react/menubar';
import { NavigationMenu } from '@tale-ui/react/navigation-menu';
import { PaymentInput } from '@tale-ui/react/payment-input';
import { RangeCalendar } from '@tale-ui/react/range-calendar';
import { Row } from '@tale-ui/react/row';
import { Select } from '@tale-ui/react/select';
import { Table } from '@tale-ui/react/table';
import { Text } from '@tale-ui/react/text';
import { TextField } from '@tale-ui/react/text-field';
import { TimeField } from '@tale-ui/react/time-field';
import { Tree } from '@tale-ui/react/tree';
import { Pencil } from 'lucide-react';
import { useState } from 'react';

// ── accordion-faq ─────────────────────────────────
function EvalAccordionFaq() {
  return (
    <Column gap="xl">
      <Text variant="heading" as="h2">Frequently Asked Questions</Text>

      <Accordion.Root>
        <Accordion.Item id="what-is-tale-ui">
          <Accordion.Header>
            <Accordion.Trigger>What is Tale UI?</Accordion.Trigger>
          </Accordion.Header>
          <Accordion.Panel>
            <Text>
              Tale UI is a comprehensive design system and React component library built on top of
              React Aria Components. It provides accessible, themeable UI primitives with consistent
              BEM-based styling, dark mode support, and a rich token system — so you can build
              polished products without reinventing the wheel.
            </Text>
          </Accordion.Panel>
        </Accordion.Item>

        <Accordion.Item id="how-to-install">
          <Accordion.Header>
            <Accordion.Trigger>How do I install it?</Accordion.Trigger>
          </Accordion.Header>
          <Accordion.Panel>
            <Text>
              Install Tale UI using pnpm: <code>pnpm add @tale-ui/react @tale-ui/react-styles</code>.
              Then import the stylesheet in your app entry point with{' '}
              <code>import '@tale-ui/react-styles'</code>, add <code>class="tale-ui"</code> and{' '}
              <code>data-color-mode="light"</code> to your <code>&lt;html&gt;</code> element, and
              you are ready to use components.
            </Text>
          </Accordion.Panel>
        </Accordion.Item>

        <Accordion.Item id="is-it-accessible">
          <Accordion.Header>
            <Accordion.Trigger>Is it accessible?</Accordion.Trigger>
          </Accordion.Header>
          <Accordion.Panel>
            <Text>
              Yes. Tale UI is built on React Aria Components, Adobe's battle-tested accessibility
              primitives. Every interactive component ships with correct ARIA roles, keyboard
              navigation, focus management, and screen reader announcements out of the box — so
              accessibility is the default, not an afterthought.
            </Text>
          </Accordion.Panel>
        </Accordion.Item>

        <Accordion.Item id="can-i-customize">
          <Accordion.Header>
            <Accordion.Trigger>Can I customize the theme?</Accordion.Trigger>
          </Accordion.Header>
          <Accordion.Panel>
            <Text>
              Absolutely. Tale UI exposes a layered CSS custom property system. You can override
              global color and spacing tokens, or use category tokens like{' '}
              <code>--field-bg</code>, <code>--popup-radius</code>, and{' '}
              <code>--modal-backdrop-bg</code> on <code>:root</code> to retheme entire component
              families at once — no CSS-in-JS or build step required.
            </Text>
          </Accordion.Panel>
        </Accordion.Item>
      </Accordion.Root>

      <Banner.Root variant="info">
        <Banner.Description>Still have questions?</Banner.Description>
        <Banner.Actions>
          <Link href="#">Contact us</Link>
        </Banner.Actions>
      </Banner.Root>
    </Column>
  );
}

// ── calendar-date ─────────────────────────────────
function EvalCalendarDate() {
  return (
    <Calendar.Root>
      <Calendar.Header>
        <Calendar.PreviousButton />
        <Calendar.Heading />
        <Calendar.NextButton />
      </Calendar.Header>
      <Calendar.Grid>
        <Calendar.GridHeader>
          {(day) => <Calendar.GridHeaderCell>{day}</Calendar.GridHeaderCell>}
        </Calendar.GridHeader>
        <Calendar.GridBody>
          {(date) => <Calendar.Cell date={date} />}
        </Calendar.GridBody>
      </Calendar.Grid>
    </Calendar.Root>
  );
}

// ── carousel-images ───────────────────────────────
function EvalCarouselImages() {
  return (
    <Carousel.Root loop style={{ width: 640, maxWidth: '100%' }}>
      <Carousel.Content>
        <Carousel.Item>
          <Image
            src="https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=640&h=360&fit=crop"
            alt="Mountain landscape"
            width={640}
            height={360}
            fit="cover"
          />
        </Carousel.Item>
        <Carousel.Item>
          <Image
            src="https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=640&h=360&fit=crop"
            alt="Ocean sunset"
            width={640}
            height={360}
            fit="cover"
          />
        </Carousel.Item>
        <Carousel.Item>
          <Image
            src="https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=640&h=360&fit=crop"
            alt="Forest path"
            width={640}
            height={360}
            fit="cover"
          />
        </Carousel.Item>
      </Carousel.Content>
      <Carousel.PreviousTrigger />
      <Carousel.NextTrigger />
      <Carousel.Indicators>
        <Carousel.Indicator index={0} />
        <Carousel.Indicator index={1} />
        <Carousel.Indicator index={2} />
      </Carousel.Indicators>
    </Carousel.Root>
  );
}

// ── color-area-picker ─────────────────────────────
function EvalColorAreaPicker() {
  return (
    <Column gap="l" style={{ width: 240 }}>
      <ColorArea.Root defaultValue="hsl(0, 100%, 50%)" xChannel="saturation" yChannel="lightness">
        <ColorArea.Thumb />
      </ColorArea.Root>

      <ColorSlider.Root channel="hue" defaultValue="hsl(0, 100%, 50%)">
        <ColorSlider.Label>Hue</ColorSlider.Label>
        <ColorSlider.Output />
        <ColorSlider.Track>
          <ColorSlider.Thumb />
        </ColorSlider.Track>
      </ColorSlider.Root>
    </Column>
  );
}

// ── context-menu-actions ──────────────────────────
function EvalContextMenuActions() {
  return (
    <ContextMenu.Root>
      <ContextMenu.Trigger>
        <div style={{
          padding: 'var(--space-xl)',
          border: '2px dashed var(--neutral-30)',
          borderRadius: 'var(--space-2xs)',
          textAlign: 'center',
        }}>
          <Text color="muted">Right-click anywhere in this area</Text>
        </div>
      </ContextMenu.Trigger>
      <ContextMenu.Popup>
        <ContextMenu.MenuList>
          <ContextMenu.Item id="edit">Edit</ContextMenu.Item>
          <ContextMenu.Item id="copy">Copy</ContextMenu.Item>
          <ContextMenu.Separator />
          <ContextMenu.Item id="delete">Delete</ContextMenu.Item>
        </ContextMenu.MenuList>
      </ContextMenu.Popup>
    </ContextMenu.Root>
  );
}

// ── data-display-cards ────────────────────────────
function EvalDataDisplayCards() {
  return (
    <Row gap="m">
      <Card.Root>
        <Card.Header>
          <Text color="muted">Revenue</Text>
        </Card.Header>
        <Card.Body>
          <Column gap="s">
            <Text variant="display">$48,200</Text>
            <Badge variant="success">+12%</Badge>
          </Column>
        </Card.Body>
      </Card.Root>

      <Card.Root>
        <Card.Header>
          <Text color="muted">Users</Text>
        </Card.Header>
        <Card.Body>
          <Column gap="s">
            <Text variant="display">12,340</Text>
            <Badge variant="success">+8%</Badge>
          </Column>
        </Card.Body>
      </Card.Root>

      <Card.Root>
        <Card.Header>
          <Text color="muted">Orders</Text>
        </Card.Header>
        <Card.Body>
          <Column gap="s">
            <Text variant="display">1,893</Text>
            <Badge variant="error">-3%</Badge>
          </Column>
        </Card.Body>
      </Card.Root>
    </Row>
  );
}

// ── date-field-input ──────────────────────────────
function EvalDateFieldInput() {
  return (
    <DateField.Root>
      <DateField.Label>Date</DateField.Label>
      <DateField.DateInput>
        {(segment) => <DateField.Segment segment={segment} />}
      </DateField.DateInput>
    </DateField.Root>
  );
}

// ── date-picker-form ──────────────────────────────
function EvalDatePickerForm() {
  return (
    <DatePicker.Root>
      <DatePicker.Label>Date</DatePicker.Label>
      <DatePicker.Group>
        <DatePicker.DateInput>
          {(segment) => <DatePicker.Segment segment={segment} />}
        </DatePicker.DateInput>
        <DatePicker.Trigger />
      </DatePicker.Group>
      <DatePicker.Popover>
        <DatePicker.Dialog>
          <Calendar.Root>
            <Calendar.Header>
              <Calendar.PreviousButton />
              <Calendar.Heading />
              <Calendar.NextButton />
            </Calendar.Header>
            <Calendar.Grid>
              <Calendar.GridHeader>
                {(day) => <Calendar.GridHeaderCell>{day}</Calendar.GridHeaderCell>}
              </Calendar.GridHeader>
              <Calendar.GridBody>
                {(date) => <Calendar.Cell date={date} />}
              </Calendar.GridBody>
            </Calendar.Grid>
          </Calendar.Root>
        </DatePicker.Dialog>
      </DatePicker.Popover>
    </DatePicker.Root>
  );
}

// ── date-range-picker-form ────────────────────────
function EvalDateRangePickerForm() {
  return (
    <DateRangePicker.Root>
      <DateRangePicker.Label>Date range</DateRangePicker.Label>
      <DateRangePicker.Group>
        <DateRangePicker.StartDate>
          {(segment) => <DateRangePicker.Segment segment={segment} />}
        </DateRangePicker.StartDate>
        <span aria-hidden="true">–</span>
        <DateRangePicker.EndDate>
          {(segment) => <DateRangePicker.Segment segment={segment} />}
        </DateRangePicker.EndDate>
        <DateRangePicker.Trigger />
      </DateRangePicker.Group>
      <DateRangePicker.Popover>
        <DateRangePicker.Dialog>
          <RangeCalendar.Root>
            <RangeCalendar.Header>
              <RangeCalendar.PreviousButton />
              <RangeCalendar.Heading />
              <RangeCalendar.NextButton />
            </RangeCalendar.Header>
            <RangeCalendar.Grid>
              <RangeCalendar.GridHeader>
                {(day) => <RangeCalendar.GridHeaderCell>{day}</RangeCalendar.GridHeaderCell>}
              </RangeCalendar.GridHeader>
              <RangeCalendar.GridBody>
                {(date) => <RangeCalendar.Cell date={date} />}
              </RangeCalendar.GridBody>
            </RangeCalendar.Grid>
          </RangeCalendar.Root>
        </DateRangePicker.Dialog>
      </DateRangePicker.Popover>
    </DateRangePicker.Root>
  );
}

// ── fieldset-address ──────────────────────────────
function EvalFieldsetAddress() {
  return (
    <Fieldset.Root>
      <Fieldset.Legend>Address</Fieldset.Legend>
      <Column gap="m">
        <TextField.Root name="street">
          <TextField.Label>Street</TextField.Label>
          <TextField.Input placeholder="123 Main St" />
        </TextField.Root>
        <Row gap="m">
          <TextField.Root name="city" style={{ flex: 1 }}>
            <TextField.Label>City</TextField.Label>
            <TextField.Input placeholder="New York" />
          </TextField.Root>
          <TextField.Root name="zip" style={{ width: 120 }}>
            <TextField.Label>ZIP Code</TextField.Label>
            <TextField.Input placeholder="10001" />
          </TextField.Root>
        </Row>
      </Column>
    </Fieldset.Root>
  );
}

// ── grid-list-gallery ─────────────────────────────
type EvalGridListGallerySelectionValue = Parameters<NonNullable<React.ComponentProps<typeof GridList.Root>['onSelectionChange']>>[0];

const EvalGridListGalleryITEMS = [
  { id: '1', src: 'https://picsum.photos/seed/forest/400/240', title: 'Forest Trail', description: 'A peaceful walk through the woods' },
  { id: '2', src: 'https://picsum.photos/seed/mountain/400/240', title: 'Mountain Peak', description: 'Stunning alpine views' },
  { id: '3', src: 'https://picsum.photos/seed/ocean/400/240', title: 'Ocean Sunset', description: 'Golden hour by the sea' },
  { id: '4', src: 'https://picsum.photos/seed/desert/400/240', title: 'Desert Dunes', description: 'Vast sandy landscapes' },
];

function EvalGridListGallery() {
  const [selectedKeys, setSelectedKeys] = useState<EvalGridListGallerySelectionValue>(new Set());

  return (
    <GridList.Root
      aria-label="Image gallery"
      selectionMode="multiple"
      selectedKeys={selectedKeys}
      onSelectionChange={setSelectedKeys}
      style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 'var(--space-m)' }}
    >
      {EvalGridListGalleryITEMS.map((item) => (
        <GridList.Item key={item.id} id={item.id} textValue={item.title}>
          <Column gap="s">
            <Image src={item.src} alt={item.title} width={400} height={200} radius="md" fit="cover" />
            <Column gap="2xs">
              <Text variant="heading">{item.title}</Text>
              <Text color="muted" size="s">{item.description}</Text>
            </Column>
          </Column>
        </GridList.Item>
      ))}
    </GridList.Root>
  );
}

// ── menubar-editor ────────────────────────────────
function EvalMenubarEditor() {
  return (
    <Menubar.Root>
      <Menubar.Item>
        <Menu.Root>
          <Menu.Trigger>File</Menu.Trigger>
          <Menu.Popover>
            <Menu.MenuList>
              <Menu.Item id="new">New</Menu.Item>
              <Menu.Item id="open">Open</Menu.Item>
              <Menu.Item id="save">Save</Menu.Item>
              <Menu.Item id="save-as">Save As</Menu.Item>
            </Menu.MenuList>
          </Menu.Popover>
        </Menu.Root>
      </Menubar.Item>
      <Menubar.Item>
        <Menu.Root>
          <Menu.Trigger>Edit</Menu.Trigger>
          <Menu.Popover>
            <Menu.MenuList>
              <Menu.Item id="undo">Undo</Menu.Item>
              <Menu.Item id="redo">Redo</Menu.Item>
              <Menu.Separator />
              <Menu.Item id="cut">Cut</Menu.Item>
              <Menu.Item id="copy">Copy</Menu.Item>
              <Menu.Item id="paste">Paste</Menu.Item>
            </Menu.MenuList>
          </Menu.Popover>
        </Menu.Root>
      </Menubar.Item>
      <Menubar.Item>
        <Menu.Root>
          <Menu.Trigger>View</Menu.Trigger>
          <Menu.Popover>
            <Menu.MenuList>
              <Menu.Item id="zoom-in">Zoom In</Menu.Item>
              <Menu.Item id="zoom-out">Zoom Out</Menu.Item>
              <Menu.Separator />
              <Menu.Item id="fullscreen">Fullscreen</Menu.Item>
            </Menu.MenuList>
          </Menu.Popover>
        </Menu.Root>
      </Menubar.Item>
    </Menubar.Root>
  );
}

// ── navigation-menu-site ──────────────────────────
function EvalNavigationMenuSite() {
  return (
    <NavigationMenu.Root>
      <NavigationMenu.List>
        <NavigationMenu.Item>
          <NavigationMenu.Link href="#">Home</NavigationMenu.Link>
        </NavigationMenu.Item>
        <NavigationMenu.Item>
          <NavigationMenu.Link href="#">Products</NavigationMenu.Link>
        </NavigationMenu.Item>
        <NavigationMenu.Item>
          <NavigationMenu.Link href="#">About</NavigationMenu.Link>
        </NavigationMenu.Item>
      </NavigationMenu.List>
    </NavigationMenu.Root>
  );
}

// ── payment-input-card ────────────────────────────
function EvalPaymentInputCard() {
  return (
    <PaymentInput.Root>
      <PaymentInput.Label>Card number</PaymentInput.Label>
      <PaymentInput.Group>
        <PaymentInput.Input placeholder="1234 5678 9012 3456" />
        <PaymentInput.CardIcon />
      </PaymentInput.Group>
    </PaymentInput.Root>
  );
}

// ── range-calendar-dates ──────────────────────────
function EvalRangeCalendarDates() {
  return (
    <RangeCalendar.Root>
      <RangeCalendar.Header>
        <RangeCalendar.PreviousButton />
        <RangeCalendar.Heading />
        <RangeCalendar.NextButton />
      </RangeCalendar.Header>
      <RangeCalendar.Grid>
        <RangeCalendar.GridHeader>
          {(day) => <RangeCalendar.GridHeaderCell>{day}</RangeCalendar.GridHeaderCell>}
        </RangeCalendar.GridHeader>
        <RangeCalendar.GridBody>
          {(date) => <RangeCalendar.Cell date={date} />}
        </RangeCalendar.GridBody>
      </RangeCalendar.Grid>
    </RangeCalendar.Root>
  );
}

// ── settings-page ─────────────────────────────────
function EvalSettingsPage() {
  return (
    <Column gap="xl">
      <Text variant="heading" as="h1">Settings</Text>

      <Row gap="m">
        <Card.Root>
          <Card.Header>
            <Text variant="heading" as="h2">Profile</Text>
          </Card.Header>
          <Card.Body>
            <Column gap="m">
              <TextField.Root>
                <TextField.Label>Name</TextField.Label>
                <TextField.Input placeholder="Jane Doe" />
              </TextField.Root>
              <TextField.Root>
                <TextField.Label>Email</TextField.Label>
                <TextField.Input placeholder="jane@example.com" />
              </TextField.Root>
            </Column>
          </Card.Body>
        </Card.Root>

        <Card.Root>
          <Card.Header>
            <Text variant="heading" as="h2">Preferences</Text>
          </Card.Header>
          <Card.Body>
            <Select.Root placeholder="Select theme...">
              <Select.Label>Theme</Select.Label>
              <Select.Trigger>
                <Select.Value />
                <Select.Icon />
              </Select.Trigger>
              <Select.Popover>
                <Select.ListBox>
                  <Select.Item id="light" textValue="Light">Light</Select.Item>
                  <Select.Item id="dark" textValue="Dark">Dark</Select.Item>
                  <Select.Item id="system" textValue="System">System</Select.Item>
                </Select.ListBox>
              </Select.Popover>
            </Select.Root>
          </Card.Body>
        </Card.Root>
      </Row>

      <Row justify="end" gap="s">
        <Button variant="ghost">Cancel</Button>
        <Button variant="primary">Save</Button>
      </Row>
    </Column>
  );
}

// ── table-data ────────────────────────────────────
const EvalTableDatarows = [
  { id: '1', name: 'Alice Johnson', role: 'Engineering Lead', status: 'Active', statusVariant: 'success' as const },
  { id: '2', name: 'Bob Martinez', role: 'Product Designer', status: 'Inactive', statusVariant: 'neutral' as const },
  { id: '3', name: 'Carol Kim', role: 'Data Analyst', status: 'Pending', statusVariant: 'warning' as const },
];

function EvalTableData() {
  return (
    <Table.Root aria-label="People">
      <Table.Header>
        <Table.Column isRowHeader>Name</Table.Column>
        <Table.Column>Role</Table.Column>
        <Table.Column>Status</Table.Column>
      </Table.Header>
      <Table.Body>
        {EvalTableDatarows.map((row) => (
          <Table.Row key={row.id} id={row.id}>
            <Table.Cell>{row.name}</Table.Cell>
            <Table.Cell>{row.role}</Table.Cell>
            <Table.Cell>
              <Badge variant={row.statusVariant}>{row.status}</Badge>
            </Table.Cell>
          </Table.Row>
        ))}
      </Table.Body>
    </Table.Root>
  );
}

// ── time-field-input ──────────────────────────────
function EvalTimeFieldInput() {
  return (
    <TimeField.Root granularity="minute">
      <TimeField.Label>Meeting Time</TimeField.Label>
      <TimeField.DateInput>
        {(segment) => <TimeField.Segment segment={segment} />}
      </TimeField.DateInput>
    </TimeField.Root>
  );
}

// ── tree-file-system ──────────────────────────────
function EvalTreeFileSystem() {
  return (
    <Tree.Root aria-label="File system" defaultExpandedKeys={new Set(['src', 'public'])}>
      <Tree.Item id="src" textValue="src">
        <Tree.ItemContent>src</Tree.ItemContent>
        <Tree.Item id="src-main" textValue="main.tsx">
          <Tree.ItemContent>main.tsx</Tree.ItemContent>
        </Tree.Item>
        <Tree.Item id="src-app" textValue="App.tsx">
          <Tree.ItemContent>App.tsx</Tree.ItemContent>
        </Tree.Item>
        <Tree.Item id="src-index" textValue="index.css">
          <Tree.ItemContent>index.css</Tree.ItemContent>
        </Tree.Item>
        <Tree.Item id="src-components" textValue="components">
          <Tree.ItemContent>components</Tree.ItemContent>
          <Tree.Item id="src-components-button" textValue="Button.tsx">
            <Tree.ItemContent>Button.tsx</Tree.ItemContent>
          </Tree.Item>
          <Tree.Item id="src-components-header" textValue="Header.tsx">
            <Tree.ItemContent>Header.tsx</Tree.ItemContent>
          </Tree.Item>
        </Tree.Item>
      </Tree.Item>
      <Tree.Item id="public" textValue="public">
        <Tree.ItemContent>public</Tree.ItemContent>
        <Tree.Item id="public-index" textValue="index.html">
          <Tree.ItemContent>index.html</Tree.ItemContent>
        </Tree.Item>
        <Tree.Item id="public-favicon" textValue="favicon.ico">
          <Tree.ItemContent>favicon.ico</Tree.ItemContent>
        </Tree.Item>
        <Tree.Item id="public-robots" textValue="robots.txt">
          <Tree.ItemContent>robots.txt</Tree.ItemContent>
        </Tree.Item>
      </Tree.Item>
    </Tree.Root>
  );
}

// ── user-profile-card ─────────────────────────────
function EvalUserProfileCard() {
  return (
    <Card.Root variant="elevated">
      <Card.Header>
        <Image src="/profile.jpg" alt="Sarah Chen" radius="full" width={80} height={80} />
      </Card.Header>
      <Card.Body>
        <Column gap="s">
          <Text variant="heading">Sarah Chen</Text>
          <Text color="muted">Senior Engineer</Text>
          <Row gap="s">
            <Badge variant="neutral">React</Badge>
            <Badge variant="neutral">TypeScript</Badge>
          </Row>
        </Column>
      </Card.Body>
      <Card.Footer>
        <Row gap="s">
          <IconButton variant="ghost" aria-label="Edit profile">
            <Icon icon={Pencil} />
          </IconButton>
          <Button variant="primary">Message</Button>
        </Row>
      </Card.Footer>
    </Card.Root>
  );
}

export default function EvalReview() {
  // Snapshot data-color-mode during render (before any child effects fire),
  // then restore it once after mount. This neutralises the showcase
  // ColorModeToggle's mount-time side effect, which would otherwise force
  // the page back to OS preference / its own localStorage every time you
  // enter or refresh /eval-review. User-initiated toggles still work because
  // they trigger ColorModeToggle's effect on a real state change.
  const [initialMode] = React.useState(() =>
    typeof document !== 'undefined'
      ? document.documentElement.getAttribute('data-color-mode')
      : null,
  );
  React.useEffect(() => {
    if (initialMode === null) {
      document.documentElement.removeAttribute('data-color-mode');
    } else {
      document.documentElement.setAttribute('data-color-mode', initialMode);
    }
  }, [initialMode]);

  return (
    <div className="eval-review">
      <div className="eval-review__header">
        <h1>Eval Review</h1>
        <p>Generated code for 20 golden prompts. Visual L4 inspection.</p>
      </div>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">accordion-faq</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Create an FAQ section with a heading that says 'Frequently Asked Questions'. Below it, add an accordion with 4 items: 'What is Tale UI?' with answer about it being a design system, 'How do I install it?' with pnpm install instructions, 'Is it accessible?' with answer about React Aria foundation, and 'Can I customize the theme?' with answer about CSS custom properties. At the bottom, add an info banner with a description that says 'Still have questions?' and a link labeled 'Contact us'.</p>
        <div className="eval-review__preview">
          <EvalAccordionFaq />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">calendar-date</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show a date calendar picker for selecting a single date.</p>
        <div className="eval-review__preview">
          <EvalCalendarDate />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">carousel-images</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show an image carousel with 3 slides, navigation buttons, and indicator dots.</p>
        <div className="eval-review__preview">
          <EvalCarouselImages />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">color-area-picker</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show a color picker using ColorArea and a hue ColorSlider — do NOT use ColorPicker.Root, do NOT use useState, do NOT import from @internationalized/color, do NOT pass an object literal to defaultValue. Use defaultValue with a plain CSS string like &quot;hsl(0, 100%, 50%)&quot; on each component.</p>
        <div className="eval-review__preview">
          <EvalColorAreaPicker />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">context-menu-actions</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show a right-click context menu with Edit, Copy, and Delete actions.</p>
        <div className="eval-review__preview">
          <EvalContextMenuActions />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">data-display-cards</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Create a row of 3 stat cards. Each card has a header with a muted label (e.g., 'Revenue', 'Users', 'Orders'), a body with a large display number (e.g., '$48,200', '12,340', '1,893'), and a badge showing a trend percentage (e.g., '+12%' success, '+8%' success, '-3%' error). Use Row to lay out the three cards horizontally. Do NOT store variant values in a data array — pass variant string literals directly in JSX (e.g. variant=&quot;success&quot;).</p>
        <div className="eval-review__preview">
          <EvalDataDisplayCards />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">date-field-input</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show a date input field with a label for entering month, day, and year.</p>
        <div className="eval-review__preview">
          <EvalDateFieldInput />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">date-picker-form</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show a date picker field with a label that opens a calendar popover for date selection.</p>
        <div className="eval-review__preview">
          <EvalDatePickerForm />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">date-range-picker-form</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show a date range picker field with a label that opens a range calendar popover.</p>
        <div className="eval-review__preview">
          <EvalDateRangePickerForm />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">fieldset-address</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show an address fieldset with street, city, and zip text fields grouped together.</p>
        <div className="eval-review__preview">
          <EvalFieldsetAddress />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">grid-list-gallery</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show a selectable grid list of 4 image cards where the user can select multiple items.</p>
        <div className="eval-review__preview">
          <EvalGridListGallery />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">menubar-editor</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show a menubar with three menus: File (New, Open, Save, Save As), Edit (Undo, Redo, Cut, Copy, Paste), and View (Zoom In, Zoom Out, Fullscreen).</p>
        <div className="eval-review__preview">
          <EvalMenubarEditor />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">navigation-menu-site</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show a site navigation bar with Home, Products, and About links.</p>
        <div className="eval-review__preview">
          <EvalNavigationMenuSite />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">payment-input-card</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show a payment card number input with a label and auto-detecting card icon.</p>
        <div className="eval-review__preview">
          <EvalPaymentInputCard />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">range-calendar-dates</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show a date range calendar for selecting a start and end date.</p>
        <div className="eval-review__preview">
          <EvalRangeCalendarDates />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">settings-page</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Create a settings page with a heading that says 'Settings'. Below the heading, display two cards side by side in a row. The first card should have a header titled 'Profile' and a body containing two text fields: one labeled 'Name' with placeholder 'Jane Doe', and one labeled 'Email' with placeholder 'jane@example.com'. The second card should have a header titled 'Preferences' and a body containing a select dropdown labeled 'Theme' with three options: Light, Dark, and System. At the bottom, add a row with a ghost Cancel button and a primary Save button, right-aligned.</p>
        <div className="eval-review__preview">
          <EvalSettingsPage />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">table-data</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show a data table with Name, Role, and Status columns and 3 rows of sample data.</p>
        <div className="eval-review__preview">
          <EvalTableData />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">time-field-input</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show a time input field with a label for selecting hours and minutes.</p>
        <div className="eval-review__preview">
          <EvalTimeFieldInput />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">tree-file-system</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Show a file system tree with folders (src, public) and files nested inside them.</p>
        <div className="eval-review__preview">
          <EvalTreeFileSystem />
        </div>
      </section>
      <section className="eval-review__section">
        <div className="eval-review__meta">
          <code className="eval-review__slug">user-profile-card</code>
          <span className="eval-review__difficulty">[complex]</span>
        </div>
        <p className="eval-review__prompt">Create a user profile card using the elevated card variant. At the top, display a profile image with large border radius. In the card body, show the user's name 'Sarah Chen' as a heading, their role 'Senior Engineer' in muted text, and a row of two badges for skills: 'React' and 'TypeScript'. In the card footer, place an icon button for editing and a primary 'Message' button.</p>
        <div className="eval-review__preview">
          <EvalUserProfileCard />
        </div>
      </section>
    </div>
  );
}
