import { generatePalette } from './utils';

const THEME_DEFINITIONS = [
  {
    id: 'harbour',
    name: 'Harbour',
    description: 'Deep teal with a warm stone neutral.',
    brandColor: '025768',
    neutralColor: '79716b',
  },
  {
    id: 'lagoon',
    name: 'Lagoon',
    description: 'Clear cyan teal with a cool mineral neutral.',
    brandColor: '006a6b',
    neutralColor: '677472',
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    description: 'Confident blue with a crisp steel neutral.',
    brandColor: '215d9a',
    neutralColor: '68717a',
  },
  {
    id: 'violet-dusk',
    name: 'Violet Dusk',
    description: 'Soft violet with a balanced slate neutral.',
    brandColor: '6552a3',
    neutralColor: '706d78',
  },
  {
    id: 'wildflower',
    name: 'Wildflower',
    description: 'Muted berry with a gently rosy neutral.',
    brandColor: '8f3d65',
    neutralColor: '746b70',
  },
  {
    id: 'terracotta',
    name: 'Terracotta',
    description: 'Earthy coral with a warm clay neutral.',
    brandColor: '9b3f35',
    neutralColor: '756b68',
  },
  {
    id: 'amber-grove',
    name: 'Amber Grove',
    description: 'Burnished amber with a soft sand neutral.',
    brandColor: '8a5a0a',
    neutralColor: '756f64',
  },
  {
    id: 'fern',
    name: 'Fern',
    description: 'Leaf green with a quiet botanical neutral.',
    brandColor: '3b6b43',
    neutralColor: '6a7169',
  },
];

/**
 * Create a complete theme from the two shade-60 anchor colours.
 * Every token preview is generated by the same OKLCH algorithm used by the
 * Theme Playground rather than stored as a hand-authored colour scale.
 */
export const createTheme = (definition) =>
  Object.freeze({
    ...definition,
    brandPalette: Object.freeze(generatePalette(`#${definition.brandColor}`, 'named')),
    neutralPalette: Object.freeze(generatePalette(`#${definition.neutralColor}`, 'neutral')),
  });

export const THEMES = Object.freeze(THEME_DEFINITIONS.map(createTheme));
export const DEFAULT_THEME_ID = 'harbour';

export const getThemeById = (themeId) => THEMES.find(({ id }) => id === themeId);

export const getThemeIdForColors = (brandColor, neutralColor) => {
  const normalizedBrand = brandColor.replace(/^#/, '').toLowerCase();
  const normalizedNeutral = neutralColor.replace(/^#/, '').toLowerCase();
  return (
    THEMES.find(
      (theme) =>
        theme.brandColor.toLowerCase() === normalizedBrand &&
        theme.neutralColor.toLowerCase() === normalizedNeutral,
    )?.id ?? null
  );
};
